// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    internal static class Afghanistan
    {
        public static Country Data { get; } = new()
        {
            Id = 1,
            Name = "Afghanistan",
            Iso3 = "AFG",
            Iso2 = "AF",
            NumericCode = "004",
            PhoneCode = "93",
            Capital = "Kabul",
            Currency = "AFN",
            CurrencyName = "Afghan afghani",
            CurrencySymbol = "؋",
            Tld = ".af",
            Native = "افغانستان",
            Region = "Asia",
            RegionId = 3,
            Subregion = "Southern Asia",
            SubregionId = 14,
            Nationality = "Afghan",
            Latitude = "33.00000000",
            Longitude = "65.00000000",
            Emoji = "🇦🇫",
            EmojiU = "U+1F1E6 U+1F1EB",
            Timezones = new()
            {
                new() { ZoneName = "Asia/Kabul", GmtOffset = 16200, GmtOffsetName = "UTC+04:30", Abbreviation = "AFT", TzName = "Afghanistan Time" }
            },
            Translations = new()
            {
                ["br"] = "Afghanistan",
                ["ko"] = "아프가니스탄",
                ["pt-BR"] = "Afeganistão",
                ["pt"] = "Afeganistão",
                ["nl"] = "Afghanistan",
                ["hr"] = "Afganistan",
                ["fa"] = "افغانستان",
                ["de"] = "Afghanistan",
                ["es"] = "Afganistán",
                ["fr"] = "Afghanistan",
                ["ja"] = "アフガニスタン",
                ["it"] = "Afghanistan",
                ["zh-CN"] = "阿富汗",
                ["tr"] = "Afganistan",
                ["ru"] = "Афганистан",
                ["uk"] = "Афганістан",
                ["pl"] = "Afganistan",
                ["ar"] = "أفغانستان",
                ["hi"] = "अफ़ग़ानिस्तान"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Badakhshan",
                    StateCode = "",
                    Latitude = "36.80402540",
                    Longitude = "71.36765800",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ashkāsham", Latitude = "36.68333000", Longitude = "71.53333000" },
                        new() { Id = 2, Name = "Fayzabad", Latitude = "37.11664000", Longitude = "70.58002000" },
                        new() { Id = 3, Name = "Jurm", Latitude = "36.86477000", Longitude = "70.83421000" },
                        new() { Id = 4, Name = "Khandūd", Latitude = "36.95127000", Longitude = "72.31800000" },
                        new() { Id = 5, Name = "Rāghistān", Latitude = "37.66079000", Longitude = "70.67346000" },
                        new() { Id = 6, Name = "Wākhān", Latitude = "37.05710000", Longitude = "73.34928000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Badghis",
                    StateCode = "",
                    Latitude = "35.00000000",
                    Longitude = "63.75000000",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ghormach", Latitude = "35.73062000", Longitude = "63.78264000" },
                        new() { Id = 2, Name = "Qala i Naw", Latitude = "34.98735000", Longitude = "63.12891000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Baghlan",
                    StateCode = "",
                    Latitude = "36.17890260",
                    Longitude = "68.74530640",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Baghlān", Latitude = "36.13068000", Longitude = "68.70829000" },
                        new() { Id = 2, Name = "Ḩukūmatī Dahanah-ye Ghōrī", Latitude = "35.90617000", Longitude = "68.48869000" },
                        new() { Id = 3, Name = "Nahrīn", Latitude = "36.06490000", Longitude = "69.13343000" },
                        new() { Id = 4, Name = "Pul-e Khumrī", Latitude = "35.94458000", Longitude = "68.71512000" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Balkh",
                    StateCode = "",
                    Latitude = "36.75506030",
                    Longitude = "66.89753720",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Balkh", Latitude = "36.75635000", Longitude = "66.89720000" },
                        new() { Id = 2, Name = "Dowlatābād", Latitude = "36.98821000", Longitude = "66.82069000" },
                        new() { Id = 3, Name = "Khulm", Latitude = "36.69736000", Longitude = "67.69826000" },
                        new() { Id = 4, Name = "Lab-Sar", Latitude = "36.02634000", Longitude = "66.83799000" },
                        new() { Id = 5, Name = "Mazār-e Sharīf", Latitude = "36.70904000", Longitude = "67.11087000" },
                        new() { Id = 6, Name = "Qarchī Gak", Latitude = "37.03999000", Longitude = "66.78891000" }
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Bamyan",
                    StateCode = "",
                    Latitude = "34.79463100",
                    Longitude = "67.68433400",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bāmyān", Latitude = "34.82156000", Longitude = "67.82734000" },
                        new() { Id = 2, Name = "Panjāb", Latitude = "34.38795000", Longitude = "67.02327000" }
                    }
                },

                new()
                {
                    Id = 6,
                    Name = "Daykundi",
                    StateCode = "",
                    Latitude = "33.72511300",
                    Longitude = "66.21965540",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Nīlī", Latitude = "33.76329000", Longitude = "66.07617000" }
                    }
                },

                new()
                {
                    Id = 7,
                    Name = "Farah",
                    StateCode = "",
                    Latitude = "32.37409070",
                    Longitude = "62.11462660",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Farah", Latitude = "32.37451000", Longitude = "62.11638000" }
                    }
                },

                new()
                {
                    Id = 8,
                    Name = "Faryab",
                    StateCode = "",
                    Latitude = "35.92617840",
                    Longitude = "64.62377580",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Andkhoy", Latitude = "36.95293000", Longitude = "65.12376000" },
                        new() { Id = 2, Name = "Maymana", Latitude = "35.92139000", Longitude = "64.78361000" }
                    }
                },

                new()
                {
                    Id = 9,
                    Name = "Ghazni",
                    StateCode = "",
                    Latitude = "33.54505870",
                    Longitude = "68.41739720",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ghazni", Latitude = "33.55391000", Longitude = "68.42096000" }
                    }
                },

                new()
                {
                    Id = 10,
                    Name = "Ghōr",
                    StateCode = "",
                    Latitude = "34.16052570",
                    Longitude = "64.92019490",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Fayrōz Kōh", Latitude = "34.51952000", Longitude = "65.25093000" },
                        new() { Id = 2, Name = "Shahrak", Latitude = "34.10737000", Longitude = "64.30520000" }
                    }
                },

                new()
                {
                    Id = 11,
                    Name = "Helmand",
                    StateCode = "",
                    Latitude = "31.00000000",
                    Longitude = "64.00000000",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "‘Alāqahdārī Dīshū", Latitude = "30.43206000", Longitude = "63.29802000" },
                        new() { Id = 2, Name = "Gereshk", Latitude = "31.82089000", Longitude = "64.57005000" },
                        new() { Id = 3, Name = "Lashkar Gāh", Latitude = "31.59382000", Longitude = "64.37161000" },
                        new() { Id = 4, Name = "Markaz-e Ḩukūmat-e Darwēshān", Latitude = "31.13231000", Longitude = "64.19340000" },
                        new() { Id = 5, Name = "Sangīn", Latitude = "32.07275000", Longitude = "64.83590000" }
                    }
                },

                new()
                {
                    Id = 12,
                    Name = "Herat",
                    StateCode = "",
                    Latitude = "34.34914430",
                    Longitude = "62.21632520",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Chahār Burj", Latitude = "34.24475000", Longitude = "62.19165000" },
                        new() { Id = 2, Name = "Ghōriyān", Latitude = "34.34480000", Longitude = "61.49321000" },
                        new() { Id = 3, Name = "Herāt", Latitude = "34.34817000", Longitude = "62.19967000" },
                        new() { Id = 4, Name = "Kafir Qala", Latitude = "34.66667000", Longitude = "61.06667000" },
                        new() { Id = 5, Name = "Karukh", Latitude = "34.48108000", Longitude = "62.58630000" },
                        new() { Id = 6, Name = "Kuhsān", Latitude = "34.65389000", Longitude = "61.19778000" },
                        new() { Id = 7, Name = "Kushk", Latitude = "33.29565000", Longitude = "61.95221000" },
                        new() { Id = 8, Name = "Qarah Bāgh", Latitude = "34.94023000", Longitude = "61.77589000" },
                        new() { Id = 9, Name = "Shīnḏanḏ", Latitude = "33.30294000", Longitude = "62.14740000" },
                        new() { Id = 10, Name = "Tīr Pul", Latitude = "34.59431000", Longitude = "61.26895000" },
                        new() { Id = 11, Name = "Zindah Jān", Latitude = "34.34264000", Longitude = "61.74675000" }
                    }
                },

                new()
                {
                    Id = 13,
                    Name = "Jowzjan",
                    StateCode = "",
                    Latitude = "36.96657060",
                    Longitude = "65.95602320",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Āqchah", Latitude = "36.90500000", Longitude = "66.18341000" },
                        new() { Id = 2, Name = "Darzāb", Latitude = "35.97744000", Longitude = "65.37828000" },
                        new() { Id = 3, Name = "Qarqīn", Latitude = "37.41853000", Longitude = "66.04358000" },
                        new() { Id = 4, Name = "Shibirghān", Latitude = "36.66757000", Longitude = "65.75290000" }
                    }
                },

                new()
                {
                    Id = 14,
                    Name = "Kabul",
                    StateCode = "",
                    Latitude = "34.52664310",
                    Longitude = "69.18490820",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Kabul", Latitude = "34.52813000", Longitude = "69.17233000" },
                        new() { Id = 2, Name = "Mīr Bachah Kōṯ", Latitude = "34.74999000", Longitude = "69.11899000" },
                        new() { Id = 3, Name = "Paghmān", Latitude = "34.58787000", Longitude = "68.95091000" }
                    }
                },

                new()
                {
                    Id = 15,
                    Name = "Kandahar",
                    StateCode = "",
                    Latitude = "31.62057380",
                    Longitude = "65.71575730",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Kandahār", Latitude = "31.61332000", Longitude = "65.71013000" }
                    }
                },

                new()
                {
                    Id = 16,
                    Name = "Kapisa",
                    StateCode = "",
                    Latitude = "34.90555600",
                    Longitude = "69.74166700",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Sidqābād", Latitude = "35.02298000", Longitude = "69.35112000" }
                    }
                },

                new()
                {
                    Id = 17,
                    Name = "Khost",
                    StateCode = "",
                    Latitude = "33.33914020",
                    Longitude = "69.92063590",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Khōst", Latitude = "33.33951000", Longitude = "69.92041000" }
                    }
                },

                new()
                {
                    Id = 18,
                    Name = "Kunar",
                    StateCode = "",
                    Latitude = "34.95000000",
                    Longitude = "71.13333300",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Asadabad", Latitude = "34.87311000", Longitude = "71.14697000" },
                        new() { Id = 2, Name = "Āsmār", Latitude = "35.03333000", Longitude = "71.35809000" }
                    }
                },

                new()
                {
                    Id = 19,
                    Name = "Kunduz Province",
                    StateCode = "",
                    Latitude = "36.87071870",
                    Longitude = "68.75635280",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Dasht-e Archī", Latitude = "37.13333000", Longitude = "69.16667000" },
                        new() { Id = 2, Name = "Imām Şāḩib", Latitude = "37.18897000", Longitude = "68.93644000" },
                        new() { Id = 3, Name = "Khanabad", Latitude = "36.68250000", Longitude = "69.11556000" },
                        new() { Id = 4, Name = "Kunduz", Latitude = "36.72895000", Longitude = "68.85700000" },
                        new() { Id = 5, Name = "Qarāwul", Latitude = "37.21959000", Longitude = "68.78020000" }
                    }
                },

                new()
                {
                    Id = 20,
                    Name = "Laghman",
                    StateCode = "",
                    Latitude = "34.78333300",
                    Longitude = "70.18333300",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Mehtar Lām", Latitude = "34.67139000", Longitude = "70.20944000" }
                    }
                },

                new()
                {
                    Id = 21,
                    Name = "Logar",
                    StateCode = "",
                    Latitude = "34.06535950",
                    Longitude = "69.16017200",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Baraki Barak", Latitude = "33.96744000", Longitude = "68.94920000" },
                        new() { Id = 2, Name = "Ḩukūmatī Azrah", Latitude = "34.17355000", Longitude = "69.64573000" },
                        new() { Id = 3, Name = "Pul-e ‘Alam", Latitude = "33.99529000", Longitude = "69.02274000" }
                    }
                },

                new()
                {
                    Id = 22,
                    Name = "Nangarhar",
                    StateCode = "",
                    Latitude = "34.22038900",
                    Longitude = "70.38003140",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bāsawul", Latitude = "34.24749000", Longitude = "70.87218000" },
                        new() { Id = 2, Name = "Jalālābād", Latitude = "34.42647000", Longitude = "70.45153000" }
                    }
                },

                new()
                {
                    Id = 23,
                    Name = "Nimruz",
                    StateCode = "",
                    Latitude = "30.77538110",
                    Longitude = "62.47930880",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Khāsh", Latitude = "31.52919000", Longitude = "62.79055000" },
                        new() { Id = 2, Name = "Mīrābād", Latitude = "30.43624000", Longitude = "61.83830000" },
                        new() { Id = 3, Name = "Rūdbār", Latitude = "30.15000000", Longitude = "62.60000000" },
                        new() { Id = 4, Name = "Zaranj", Latitude = "30.95962000", Longitude = "61.86037000" }
                    }
                },

                new()
                {
                    Id = 24,
                    Name = "Nuristan",
                    StateCode = "",
                    Latitude = "35.30000000",
                    Longitude = "70.83333300",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Pārūn", Latitude = "35.42064000", Longitude = "70.92261000" }
                    }
                },

                new()
                {
                    Id = 25,
                    Name = "Paktia",
                    StateCode = "",
                    Latitude = "33.70572400",
                    Longitude = "69.40835550",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Gardez", Latitude = "33.59744000", Longitude = "69.22592000" }
                    }
                },

                new()
                {
                    Id = 26,
                    Name = "Paktika",
                    StateCode = "",
                    Latitude = "32.39362310",
                    Longitude = "68.70365140",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Saṟōbī", Latitude = "32.75221000", Longitude = "69.04587000" },
                        new() { Id = 2, Name = "Zaṟah Sharan", Latitude = "33.14641000", Longitude = "68.79213000" },
                        new() { Id = 3, Name = "Zarghūn Shahr", Latitude = "32.84734000", Longitude = "68.44573000" }
                    }
                },

                new()
                {
                    Id = 27,
                    Name = "Panjshir",
                    StateCode = "",
                    Latitude = "35.69735560",
                    Longitude = "70.09996040",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bāzārak", Latitude = "35.31292000", Longitude = "69.51519000" }
                    }
                },

                new()
                {
                    Id = 28,
                    Name = "Parwan",
                    StateCode = "",
                    Latitude = "34.97970140",
                    Longitude = "68.91467030",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Charikar", Latitude = "35.01361000", Longitude = "69.17139000" },
                        new() { Id = 2, Name = "Jabal os Saraj", Latitude = "35.11833000", Longitude = "69.23778000" }
                    }
                },

                new()
                {
                    Id = 29,
                    Name = "Samangan",
                    StateCode = "",
                    Latitude = "36.26749380",
                    Longitude = "68.02153740",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Aībak", Latitude = "36.26468000", Longitude = "68.01551000" }
                    }
                },

                new()
                {
                    Id = 30,
                    Name = "Sar-e Pol",
                    StateCode = "",
                    Latitude = "36.21662800",
                    Longitude = "65.93336000",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Chīras", Latitude = "35.41674000", Longitude = "65.98234000" },
                        new() { Id = 2, Name = "Larkird", Latitude = "35.48936000", Longitude = "66.66409000" },
                        new() { Id = 3, Name = "Qal‘ah-ye Shahr", Latitude = "35.54729000", Longitude = "65.56760000" },
                        new() { Id = 4, Name = "Sang-e Chārak", Latitude = "35.84972000", Longitude = "66.43694000" },
                        new() { Id = 5, Name = "Sar-e Pul", Latitude = "36.21544000", Longitude = "65.93249000" },
                        new() { Id = 6, Name = "Tagāw-Bāy", Latitude = "35.69941000", Longitude = "66.06164000" },
                        new() { Id = 7, Name = "Tukzār", Latitude = "35.94831000", Longitude = "66.42132000" }
                    }
                },

                new()
                {
                    Id = 31,
                    Name = "Takhar",
                    StateCode = "",
                    Latitude = "36.59407320",
                    Longitude = "69.79389960",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ārt Khwājah", Latitude = "37.08571000", Longitude = "69.47958000" },
                        new() { Id = 2, Name = "Taloqan", Latitude = "36.73605000", Longitude = "69.53451000" }
                    }
                },

                new()
                {
                    Id = 32,
                    Name = "Urozgan",
                    StateCode = "",
                    Latitude = "32.81296810",
                    Longitude = "66.01831850",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Tarinkot", Latitude = "32.62998000", Longitude = "65.87806000" },
                        new() { Id = 2, Name = "Uruzgān", Latitude = "32.92775000", Longitude = "66.63253000" }
                    }
                },

                new()
                {
                    Id = 33,
                    Name = "Wardak",
                    StateCode = "",
                    Latitude = "34.30000000",
                    Longitude = "68.50000000",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Chaki Wardak", Latitude = "34.29000000", Longitude = "68.58000000" },
                        new() { Id = 2, Name = "Day Mirdad", Latitude = "34.50000000", Longitude = "69.00000000" },
                        new() { Id = 3, Name = "Hisa-i-Awali Bihsud", Latitude = "34.65000000", Longitude = "68.18000000" },
                        new() { Id = 4, Name = "Jaghatu", Latitude = "34.08000000", Longitude = "68.45000000" },
                        new() { Id = 5, Name = "Jalrez", Latitude = "34.52000000", Longitude = "68.78000000" },
                        new() { Id = 6, Name = "Maidan Shahr", Latitude = "34.38000000", Longitude = "68.54000000" },
                        new() { Id = 7, Name = "Markaz-i-Bihsud", Latitude = "34.55000000", Longitude = "67.80000000" },
                        new() { Id = 8, Name = "Nerkh", Latitude = "34.49000000", Longitude = "68.51000000" },
                        new() { Id = 9, Name = "Sayed Abad", Latitude = "34.00000000", Longitude = "68.63000000" }
                    }
                },

                new()
                {
                    Id = 34,
                    Name = "Zabul",
                    StateCode = "",
                    Latitude = "32.30689420",
                    Longitude = "67.12990400",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Qalāt", Latitude = "32.10575000", Longitude = "66.90833000" }
                    }
                }
            }
        };
    }
}
