// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Antarctica
    {
        public static Country Data { get; } = new Country
        {
            Id = 9,
            Name = "Antarctica",
            Iso3 = "ATA",
            Iso2 = "AQ",
            NumericCode = "010",
            PhoneCode = "672",
            Capital = "",
            Currency = "AAD",
            CurrencyName = "Antarctican dollar",
            CurrencySymbol = "$",
            Tld = ".aq",
            Native = "Antarctica",
            Region = "Polar",
            RegionId = 6,
            Subregion = "",
            SubregionId = 0,
            Nationality = "Antarctic",
            Latitude = "-74.65000000",
            Longitude = "4.48000000",
            Emoji = "🇦🇶",
            EmojiU = "U+1F1E6 U+1F1F6",
            Timezones = new List<Timezone>
            {
                new Timezone
                {
                    ZoneName = "Antarctica/Casey",
                    GmtOffset = 39600,
                    GmtOffsetName = "UTC+11:00",
                    Abbreviation = "AWST",
                    TzName = "Australian Western Standard Time"
                },
                new Timezone
                {
                    ZoneName = "Antarctica/Davis",
                    GmtOffset = 25200,
                    GmtOffsetName = "UTC+07:00",
                    Abbreviation = "DAVT",
                    TzName = "Davis Time"
                }
                new Timezone
                {
                    ZoneName = "Antarctica/DumontDUrville",
                    GmtOffset = 36000,
                    GmtOffsetName = "UTC+10:00",
                    Abbreviation = "DDUT",
                    TzName = "Dumont d'Urville Time"
                }
                new Timezone
                {
                    ZoneName = "Antarctica/Mawson",
                    GmtOffset = 18000,
                    GmtOffsetName = "UTC+05:00",
                    Abbreviation = "MAWT",
                    TzName = "Mawson Station Time"
                }
                new Timezone
                {
                    ZoneName = "Antarctica/McMurdo",
                    GmtOffset = 46800,
                    GmtOffsetName = "UTC+13:00",
                    Abbreviation = "NZDT",
                    TzName = "New Zealand Daylight Time"
                }
                new Timezone
                {
                    ZoneName = "Antarctica/Palmer",
                    GmtOffset = -10800,
                    GmtOffsetName = "UTC-03:00",
                    Abbreviation = "CLST",
                    TzName = "Chile Summer Time"
                }
                new Timezone
                {
                    ZoneName = "Antarctica/Rothera",
                    GmtOffset = -10800,
                    GmtOffsetName = "UTC-03:00",
                    Abbreviation = "ROTT",
                    TzName = "Rothera Research Station Time"
                }
                new Timezone
                {
                    ZoneName = "Antarctica/Syowa",
                    GmtOffset = 10800,
                    GmtOffsetName = "UTC+03:00",
                    Abbreviation = "SYOT",
                    TzName = "Showa Station Time"
                }
                new Timezone
                {
                    ZoneName = "Antarctica/Troll",
                    GmtOffset = 0,
                    GmtOffsetName = "UTC±00",
                    Abbreviation = "GMT",
                    TzName = "Greenwich Mean Time"
                }
                new Timezone
                {
                    ZoneName = "Antarctica/Vostok",
                    GmtOffset = 21600,
                    GmtOffsetName = "UTC+06:00",
                    Abbreviation = "VOST",
                    TzName = "Vostok Station Time"
                }
            },
            Translations = new Dictionary<string, string>
            {
                { "ko" = "남극" },
                { "pt-BR" = "Antártida" }
                { "pt" = "Antárctida" }
                { "nl" = "Antarctica" }
                { "hr" = "Antarktika" }
                { "fa" = "جنوبگان" }
                { "de" = "Antarktika" }
                { "es" = "Antártida" }
                { "fr" = "Antarctique" }
                { "ja" = "南極大陸" }
                { "it" = "Antartide" }
                { "zh-CN" = "南极洲" }
                { "tr" = "Antartika" }
                { "ru" = "Антарктида" }
                { "uk" = "Антарктида" }
                { "pl" = "Antarktyda" }
            },
            States = new List<State>
            {
            }
        };
    }
}
