// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    internal static class Bahrain
    {
        public static Country Data { get; } = new()
        {
            Id = 17,
            Name = "Bahrain",
            Iso3 = "BHR",
            Iso2 = "BH",
            NumericCode = "048",
            PhoneCode = "973",
            Capital = "Manama",
            Currency = "BHD",
            CurrencyName = "Bahraini dinar",
            CurrencySymbol = ".د.ب",
            Tld = ".bh",
            Native = "‏البحرين",
            Region = "Asia",
            RegionId = 3,
            Subregion = "Western Asia",
            SubregionId = 11,
            Nationality = "Bahraini",
            Latitude = "26.00000000",
            Longitude = "50.55000000",
            Emoji = "🇧🇭",
            EmojiU = "U+1F1E7 U+1F1ED",
            Timezones = new()
            {
                new() { ZoneName = "Asia/Bahrain", GmtOffset = 10800, GmtOffsetName = "UTC+03:00", Abbreviation = "AST", TzName = "Arabia Standard Time" }
            },
            Translations = new()
            {
                ["br"] = "Bahrein",
                ["ko"] = "바레인",
                ["pt-BR"] = "Bahrein",
                ["pt"] = "Barém",
                ["nl"] = "Bahrein",
                ["hr"] = "Bahrein",
                ["fa"] = "بحرین",
                ["de"] = "Bahrain",
                ["es"] = "Bahrein",
                ["fr"] = "Bahreïn",
                ["ja"] = "バーレーン",
                ["it"] = "Bahrein",
                ["zh-CN"] = "巴林",
                ["tr"] = "Bahreyn",
                ["ru"] = "Бахрейн",
                ["uk"] = "Бахрейн",
                ["pl"] = "Bahrajn",
                ["hi"] = "बहरीन",
                ["ar"] = "البحرين"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Capital",
                    StateCode = "",
                    Latitude = "26.42432330",
                    Longitude = "50.47472510",
                    Type = "governorate",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Jidd Ḩafş", Latitude = "26.21861000", Longitude = "50.54778000" },
                        new() { Id = 2, Name = "Manama", Latitude = "26.22787000", Longitude = "50.58565000" },
                        new() { Id = 3, Name = "Sitrah", Latitude = "26.15472000", Longitude = "50.62056000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Muharraq",
                    StateCode = "",
                    Latitude = "26.24659460",
                    Longitude = "50.61641270",
                    Type = "governorate",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Al Ḩadd", Latitude = "26.24556000", Longitude = "50.65417000" },
                        new() { Id = 2, Name = "Al Muharraq", Latitude = "26.25722000", Longitude = "50.61194000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Northern",
                    StateCode = "",
                    Latitude = "26.27784770",
                    Longitude = "50.41811230",
                    Type = "governorate",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Madīnat Ḩamad", Latitude = "26.11528000", Longitude = "50.50694000" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Southern",
                    StateCode = "",
                    Latitude = "25.84000690",
                    Longitude = "50.59026930",
                    Type = "governorate",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ar Rifā‘", Latitude = "26.13000000", Longitude = "50.55500000" },
                        new() { Id = 2, Name = "Dār Kulayb", Latitude = "26.06861000", Longitude = "50.50389000" },
                        new() { Id = 3, Name = "Madīnat ‘Īsá", Latitude = "26.17361000", Longitude = "50.54778000" }
                    }
                }
            }
        };
    }
}
