// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class CaymanIslands
    {
        public static Country Data { get; } = new()
        {
            Id = 41,
            Name = "Cayman Islands",
            Iso3 = "CYM",
            Iso2 = "KY",
            NumericCode = "136",
            PhoneCode = "1",
            Capital = "George Town",
            Currency = "KYD",
            CurrencyName = "Cayman Islands dollar",
            CurrencySymbol = "$",
            Tld = ".ky",
            Native = "Cayman Islands",
            Region = "Americas",
            RegionId = 2,
            Subregion = "Caribbean",
            SubregionId = 7,
            Nationality = "Caymanian",
            Latitude = "19.50000000",
            Longitude = "-80.50000000",
            Emoji = "🇰🇾",
            EmojiU = "U+1F1F0 U+1F1FE",
            Timezones = new()
            {
                new() { ZoneName = "America/Cayman", GmtOffset = -18000, GmtOffsetName = "UTC-05:00", Abbreviation = "EST", TzName = "Eastern Standard Time (North America" }
            },
            Translations = new()
            {
                ["br"] = "Inizi Cayman",
                ["ko"] = "케이먼 제도",
                ["pt-BR"] = "Ilhas Cayman",
                ["pt"] = "Ilhas Caimão",
                ["nl"] = "Caymaneilanden",
                ["hr"] = "Kajmanski otoci",
                ["fa"] = "جزایر کیمن",
                ["de"] = "Kaimaninseln",
                ["es"] = "Islas Caimán",
                ["fr"] = "Îles Caïmans",
                ["ja"] = "ケイマン諸島",
                ["it"] = "Isole Cayman",
                ["zh-CN"] = "开曼群岛",
                ["tr"] = "Cayman Adalari",
                ["ru"] = "Каймановы острова",
                ["uk"] = "Кайманові острови",
                ["pl"] = "Kajmany",
                ["hi"] = "केमन द्वीपसमूह",
                ["ar"] = "جزر كايمان"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Cayman Brac",
                    StateCode = "",
                    Latitude = "19.71988620",
                    Longitude = "-79.79314000",
                    Type = "",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Cayman Brac", Latitude = "19.71999700", Longitude = "-79.89072660" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Grand Cayman",
                    StateCode = "",
                    Latitude = "19.32984710",
                    Longitude = "-81.17122160",
                    Type = "",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bodden Town", Latitude = "19.27966930", Longitude = "-81.27779990" },
                        new() { Id = 2, Name = "East End", Latitude = "19.29958980", Longitude = "-81.11961380" },
                        new() { Id = 3, Name = "George Town", Latitude = "19.29023260", Longitude = "-81.44333720" },
                        new() { Id = 4, Name = "North Side", Latitude = "19.33620470", Longitude = "-81.51398130" },
                        new() { Id = 5, Name = "West Bay", Latitude = "19.36651530", Longitude = "-81.43170260" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Little Cayman",
                    StateCode = "",
                    Latitude = "19.68533460",
                    Longitude = "-80.04778240",
                    Type = "",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Little Cayman", Latitude = "19.68567390", Longitude = "-80.11830190" }
                    }
                }
            }
        };
    }
}
