// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class CocosKeelingIslands
    {
        public static Country Data { get; } = new()
        {
            Id = 47,
            Name = "Cocos (Keeling) Islands",
            Iso3 = "CCK",
            Iso2 = "CC",
            NumericCode = "166",
            PhoneCode = "61",
            Capital = "West Island",
            Currency = "AUD",
            CurrencyName = "Australian dollar",
            CurrencySymbol = "$",
            Tld = ".cc",
            Native = "Cocos (Keeling) Islands",
            Region = "Oceania",
            RegionId = 5,
            Subregion = "Australia and New Zealand",
            SubregionId = 19,
            Nationality = "Cocos Island",
            Latitude = "-12.50000000",
            Longitude = "96.83333333",
            Emoji = "🇨🇨",
            EmojiU = "U+1F1E8 U+1F1E8",
            Timezones = new()
            {
                new() { ZoneName = "Indian/Cocos", GmtOffset = 23400, GmtOffsetName = "UTC+06:30", Abbreviation = "CCT", TzName = "Cocos Islands Time" }
            },
            Translations = new()
            {
                { "ko" = "코코스 제도" },
                { "pt-BR" = "Ilhas Cocos" }
                { "pt" = "Ilhas dos Cocos" }
                { "nl" = "Cocoseilanden" }
                { "hr" = "Kokosovi Otoci" }
                { "fa" = "جزایر کوکوس" }
                { "de" = "Kokosinseln" }
                { "es" = "Islas Cocos o Islas Keeling" }
                { "fr" = "Îles Cocos" }
                { "ja" = "ココス（キーリング）諸島" }
                { "it" = "Isole Cocos e Keeling" }
                { "zh-CN" = "科科斯（基林）群岛" }
                { "tr" = "Cocos Adalari" }
                { "ru" = "Кокосовые (Килинг) острова" }
                { "uk" = "Кокосові (Кілінг) острови" }
                { "pl" = "Wyspy Kokosowe (Keelinga)" }
            },
            States = new()
            {
            }
        };
    }
}
