// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Dominica
    {
        public static Country Data { get; } = new Country
        {
            Id = 62,
            Name = "Dominica",
            Iso3 = "DMA",
            Iso2 = "DM",
            NumericCode = "212",
            PhoneCode = "1",
            Capital = "Roseau",
            Currency = "XCD",
            CurrencyName = "Eastern Caribbean dollar",
            CurrencySymbol = "$",
            Tld = ".dm",
            Native = "Dominica",
            Region = "Americas",
            RegionId = 2,
            Subregion = "Caribbean",
            SubregionId = 7,
            Nationality = "Dominican",
            Latitude = "15.41666666",
            Longitude = "-61.33333333",
            Emoji = "🇩🇲",
            EmojiU = "U+1F1E9 U+1F1F2",
            Timezones = new List<Timezone>
            {
                new Timezone
                {
                    ZoneName = "America/Dominica",
                    GmtOffset = -14400,
                    GmtOffsetName = "UTC-04:00",
                    Abbreviation = "AST",
                    TzName = "Atlantic Standard Time"
                }
            },
            Translations = new Dictionary<string, string>
            {
                { "ko" = "도미니카 연방" },
                { "pt-BR" = "Dominica" }
                { "pt" = "Dominica" }
                { "nl" = "Dominica" }
                { "hr" = "Dominika" }
                { "fa" = "دومینیکا" }
                { "de" = "Dominica" }
                { "es" = "Dominica" }
                { "fr" = "Dominique" }
                { "ja" = "ドミニカ国" }
                { "it" = "Dominica" }
                { "zh-CN" = "多米尼加" }
                { "tr" = "Dominika" }
                { "ru" = "Доминика" }
                { "uk" = "Домініка" }
                { "pl" = "Dominika" }
            },
            States = new List<State>
            {

                new State
                {
                    Id = 1,
                    Name = "Saint Andrew",
                    StateCode = "02",
                    Latitude = "",
                    Longitude = "",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Calibishie",
                            Latitude = "15.59297000",
                            Longitude = "-61.34901000"
                        },

                        new City
                        {
                            Id = 2,
                            Name = "Marigot",
                            Latitude = "15.53886000",
                            Longitude = "-61.28375000"
                        },

                        new City
                        {
                            Id = 3,
                            Name = "Wesley",
                            Latitude = "15.56667000",
                            Longitude = "-61.31667000"
                        },

                        new City
                        {
                            Id = 4,
                            Name = "Woodford Hill",
                            Latitude = "15.58093000",
                            Longitude = "-61.33149000"
                        }
                    }
                },

                new State
                {
                    Id = 2,
                    Name = "Saint David",
                    StateCode = "03",
                    Latitude = "",
                    Longitude = "",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Castle Bruce",
                            Latitude = "15.44397000",
                            Longitude = "-61.25723000"
                        },

                        new City
                        {
                            Id = 2,
                            Name = "Rosalie",
                            Latitude = "15.36667000",
                            Longitude = "-61.26667000"
                        }
                    }
                }

                new State
                {
                    Id = 3,
                    Name = "Saint George",
                    StateCode = "04",
                    Latitude = "",
                    Longitude = "",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Roseau",
                            Latitude = "15.30174000",
                            Longitude = "-61.38808000"
                        }
                    }
                }

                new State
                {
                    Id = 4,
                    Name = "Saint John",
                    StateCode = "05",
                    Latitude = "",
                    Longitude = "",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Portsmouth",
                            Latitude = "15.58333000",
                            Longitude = "-61.46667000"
                        }
                    }
                }

                new State
                {
                    Id = 5,
                    Name = "Saint Joseph",
                    StateCode = "06",
                    Latitude = "39.02227120",
                    Longitude = "-94.71765040",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Saint Joseph",
                            Latitude = "15.40000000",
                            Longitude = "-61.43333000"
                        },

                        new City
                        {
                            Id = 2,
                            Name = "Salisbury",
                            Latitude = "15.43689000",
                            Longitude = "-61.43637000"
                        }
                    }
                }

                new State
                {
                    Id = 6,
                    Name = "Saint Luke",
                    StateCode = "07",
                    Latitude = "42.10513630",
                    Longitude = "-80.05707220",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Pointe Michel",
                            Latitude = "15.25976000",
                            Longitude = "-61.37452000"
                        }
                    }
                }

                new State
                {
                    Id = 7,
                    Name = "Saint Mark",
                    StateCode = "08",
                    Latitude = "",
                    Longitude = "",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Soufrière",
                            Latitude = "15.23374000",
                            Longitude = "-61.35881000"
                        }
                    }
                }

                new State
                {
                    Id = 8,
                    Name = "Saint Patrick",
                    StateCode = "09",
                    Latitude = "",
                    Longitude = "",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Berekua",
                            Latitude = "15.23333000",
                            Longitude = "-61.31667000"
                        },

                        new City
                        {
                            Id = 2,
                            Name = "La Plaine",
                            Latitude = "15.32768000",
                            Longitude = "-61.24753000"
                        }
                    }
                }

                new State
                {
                    Id = 9,
                    Name = "Saint Paul",
                    StateCode = "10",
                    Latitude = "38.86146000",
                    Longitude = "-90.74356190",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Mahaut",
                            Latitude = "15.36357000",
                            Longitude = "-61.39701000"
                        },

                        new City
                        {
                            Id = 2,
                            Name = "Pont Cassé",
                            Latitude = "15.36667000",
                            Longitude = "-61.35000000"
                        }
                    }
                }

                new State
                {
                    Id = 10,
                    Name = "Saint Peter",
                    StateCode = "11",
                    Latitude = "40.45241940",
                    Longitude = "-80.00850560",
                    Type = "parish",
                    Cities = new List<City>
                    {

                        new City
                        {
                            Id = 1,
                            Name = "Colihaut",
                            Latitude = "15.48478000",
                            Longitude = "-61.46215000"
                        }
                    }
                }
            }
        };
    }
}
