// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    internal static class FrenchGuiana
    {
        public static Country Data { get; } = new()
        {
            Id = 76,
            Name = "French Guiana",
            Iso3 = "GUF",
            Iso2 = "GF",
            NumericCode = "254",
            PhoneCode = "594",
            Capital = "Cayenne",
            Currency = "EUR",
            CurrencyName = "Euro",
            CurrencySymbol = "€",
            Tld = ".gf",
            Native = "Guyane française",
            Region = "Americas",
            RegionId = 2,
            Subregion = "South America",
            SubregionId = 8,
            Nationality = "French Guianese",
            Latitude = "4.00000000",
            Longitude = "-53.00000000",
            Emoji = "🇬🇫",
            EmojiU = "U+1F1EC U+1F1EB",
            Timezones = new()
            {
                new() { ZoneName = "America/Cayenne", GmtOffset = -10800, GmtOffsetName = "UTC-03:00", Abbreviation = "GFT", TzName = "French Guiana Time" }
            },
            Translations = new()
            {
                ["br"] = "Gwiana",
                ["ko"] = "프랑스령 기아나",
                ["pt-BR"] = "Guiana Francesa",
                ["pt"] = "Guiana Francesa",
                ["nl"] = "Frans-Guyana",
                ["hr"] = "Francuska Gvajana",
                ["fa"] = "گویان فرانسه",
                ["de"] = "Französisch Guyana",
                ["es"] = "Guayana Francesa",
                ["fr"] = "Guayane",
                ["ja"] = "フランス領ギアナ",
                ["it"] = "Guyana francese",
                ["zh-CN"] = "法属圭亚那",
                ["tr"] = "Fransiz Guyanasi",
                ["ru"] = "Французская Гвиана",
                ["uk"] = "Французька Гвіана",
                ["pl"] = "Gujana Francuska",
                ["hi"] = "फ्रेंच गुआना",
                ["ar"] = "غويانا الفرنسية"
            },
            States = new()
            {
            }
        };
    }
}
