// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Greenland
    {
        public static Country Data { get; } = new()
        {
            Id = 86,
            Name = "Greenland",
            Iso3 = "GRL",
            Iso2 = "GL",
            NumericCode = "304",
            PhoneCode = "299",
            Capital = "Nuuk",
            Currency = "DKK",
            CurrencyName = "Danish krone",
            CurrencySymbol = "Kr.",
            Tld = ".gl",
            Native = "Kalaallit Nunaat",
            Region = "Americas",
            RegionId = 2,
            Subregion = "Northern America",
            SubregionId = 6,
            Nationality = "Greenlandic",
            Latitude = "72.00000000",
            Longitude = "-40.00000000",
            Emoji = "🇬🇱",
            EmojiU = "U+1F1EC U+1F1F1",
            Timezones = new()
            {
                new() { ZoneName = "America/Danmarkshavn", GmtOffset = 0, GmtOffsetName = "UTC±00", Abbreviation = "GMT", TzName = "Greenwich Mean Time" },
                new() { ZoneName = "America/Nuuk", GmtOffset = -10800, GmtOffsetName = "UTC-03:00", Abbreviation = "WGT", TzName = "West Greenland Time" },
                new() { ZoneName = "America/Scoresbysund", GmtOffset = -3600, GmtOffsetName = "UTC-01:00", Abbreviation = "EGT", TzName = "Eastern Greenland Time" },
                new() { ZoneName = "America/Thule", GmtOffset = -14400, GmtOffsetName = "UTC-04:00", Abbreviation = "AST", TzName = "Atlantic Standard Time" }
            },
            Translations = new()
            {
                { "ko" = "그린란드" },
                { "pt-BR" = "Groelândia" }
                { "pt" = "Gronelândia" }
                { "nl" = "Groenland" }
                { "hr" = "Grenland" }
                { "fa" = "گرینلند" }
                { "de" = "Grönland" }
                { "es" = "Groenlandia" }
                { "fr" = "Groenland" }
                { "ja" = "グリーンランド" }
                { "it" = "Groenlandia" }
                { "zh-CN" = "格陵兰岛" }
                { "tr" = "Grönland" }
                { "ru" = "Гренландия" }
                { "uk" = "Гренландія" }
                { "pl" = "Grenlandia" }
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Avannaata",
                    StateCode = "AV",
                    Latitude = "74.10267430",
                    Longitude = "-78.98755600",
                    Type = "municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ilulissat", Latitude = "69.22794880", Longitude = "-51.12805390" },
                        new() { Id = 2, Name = "Qaanaaq", Latitude = "77.46740090", Longitude = "-69.24837110" },
                        new() { Id = 3, Name = "Upernavik", Latitude = "72.78686030", Longitude = "-56.16236710" },
                        new() { Id = 4, Name = "Uummannaq", Latitude = "70.67868970", Longitude = "-52.14978240" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Kujalleq",
                    StateCode = "KU",
                    Latitude = "61.16666930",
                    Longitude = "-50.50997880",
                    Type = "municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Nanortalik", Latitude = "60.14308250", Longitude = "-45.25629050" },
                        new() { Id = 2, Name = "Narsaq", Latitude = "60.91140780", Longitude = "-46.06857080" },
                        new() { Id = 3, Name = "Qaqortoq", Latitude = "60.71959600", Longitude = "-46.05481630" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Qeqertalik",
                    StateCode = "QT",
                    Latitude = "68.82495530",
                    Longitude = "-54.76224720",
                    Type = "municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Aasiaat", Latitude = "68.70762800", Longitude = "-52.89951360" },
                        new() { Id = 2, Name = "Kangaatsiaq", Latitude = "68.30818450", Longitude = "-53.47685330" },
                        new() { Id = 3, Name = "Qasigiannguit", Latitude = "68.81986320", Longitude = "-51.20916370" },
                        new() { Id = 4, Name = "Qeqertarsuaq", Latitude = "69.24430370", Longitude = "-53.56440060" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Qeqqata",
                    StateCode = "QE",
                    Latitude = "66.08057190",
                    Longitude = "-54.26546390",
                    Type = "municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Maniitsoq", Latitude = "65.40657990", Longitude = "-52.94225730" },
                        new() { Id = 2, Name = "Sisimiut", Latitude = "66.93945740", Longitude = "-53.74567660" }
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Sermersooq",
                    StateCode = "SM",
                    Latitude = "65.08230580",
                    Longitude = "-57.28311950",
                    Type = "municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ammassalik", Latitude = "65.61452670", Longitude = "-37.65014660" },
                        new() { Id = 2, Name = "Ittoqqortoormiit", Latitude = "70.48634210", Longitude = "-21.97986600" },
                        new() { Id = 3, Name = "Ivittuut", Latitude = "61.20651840", Longitude = "-48.18198510" },
                        new() { Id = 4, Name = "Nuuk", Latitude = "64.17910090", Longitude = "-51.74800910" },
                        new() { Id = 5, Name = "Paamiut", Latitude = "62.00259620", Longitude = "-49.70519590" }
                    }
                }
            }
        };
    }
}
