// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Lesotho
    {
        public static Country Data { get; } = new()
        {
            Id = 121,
            Name = "Lesotho",
            Iso3 = "LSO",
            Iso2 = "LS",
            NumericCode = "426",
            PhoneCode = "266",
            Capital = "Maseru",
            Currency = "LSL",
            CurrencyName = "Lesotho loti",
            CurrencySymbol = "L",
            Tld = ".ls",
            Native = "Lesotho",
            Region = "Africa",
            RegionId = 1,
            Subregion = "Southern Africa",
            SubregionId = 5,
            Nationality = "Basotho",
            Latitude = "-29.50000000",
            Longitude = "28.50000000",
            Emoji = "🇱🇸",
            EmojiU = "U+1F1F1 U+1F1F8",
            Timezones = new()
            {
                new() { ZoneName = "Africa/Maseru", GmtOffset = 7200, GmtOffsetName = "UTC+02:00", Abbreviation = "SAST", TzName = "South African Standard Time" }
            },
            Translations = new()
            {
                ["br"] = "Lesotho",
                ["ko"] = "레소토",
                ["pt-BR"] = "Lesoto",
                ["pt"] = "Lesoto",
                ["nl"] = "Lesotho",
                ["hr"] = "Lesoto",
                ["fa"] = "لسوتو",
                ["de"] = "Lesotho",
                ["es"] = "Lesotho",
                ["fr"] = "Lesotho",
                ["ja"] = "レソト",
                ["it"] = "Lesotho",
                ["zh-CN"] = "莱索托",
                ["tr"] = "Lesotho",
                ["ru"] = "Лесото",
                ["uk"] = "Лесото",
                ["pl"] = "Lesotho",
                ["hi"] = "लिसोटो",
                ["ar"] = "ليسوتو"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Berea",
                    StateCode = "",
                    Latitude = "-29.19639710",
                    Longitude = "27.91755810",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Teyateyaneng", Latitude = "-29.14719000", Longitude = "27.74895000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Butha-Buthe",
                    StateCode = "",
                    Latitude = "-28.76537540",
                    Longitude = "28.24681480",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Butha-Buthe", Latitude = "-28.76659000", Longitude = "28.24937000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Leribe",
                    StateCode = "",
                    Latitude = "-28.86689100",
                    Longitude = "28.05794080",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Leribe", Latitude = "-28.87185000", Longitude = "28.04501000" },
                        new() { Id = 2, Name = "Maputsoe", Latitude = "-28.88660000", Longitude = "27.89915000" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Mafeteng",
                    StateCode = "",
                    Latitude = "-29.78930490",
                    Longitude = "27.44231930",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Mafeteng", Latitude = "-29.82299000", Longitude = "27.23744000" }
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Maseru",
                    StateCode = "",
                    Latitude = "-29.58169420",
                    Longitude = "27.82432080",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Maseru", Latitude = "-29.31667000", Longitude = "27.48333000" },
                        new() { Id = 2, Name = "Nako", Latitude = "-29.61667000", Longitude = "27.76667000" }
                    }
                },

                new()
                {
                    Id = 6,
                    Name = "Mohale's Hoek",
                    StateCode = "",
                    Latitude = "-30.15163050",
                    Longitude = "27.47701130",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Mohale’s Hoek", Latitude = "-30.15137000", Longitude = "27.47691000" }
                    }
                },

                new()
                {
                    Id = 7,
                    Name = "Mokhotlong",
                    StateCode = "",
                    Latitude = "-29.21906970",
                    Longitude = "29.03513690",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Mokhotlong", Latitude = "-29.28939000", Longitude = "29.06751000" }
                    }
                },

                new()
                {
                    Id = 8,
                    Name = "Qacha's Nek",
                    StateCode = "",
                    Latitude = "-30.11145650",
                    Longitude = "28.67897900",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Qacha’s Nek", Latitude = "-30.11537000", Longitude = "28.68936000" }
                    }
                },

                new()
                {
                    Id = 9,
                    Name = "Quthing",
                    StateCode = "",
                    Latitude = "-30.40156870",
                    Longitude = "27.70801330",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Quthing", Latitude = "-30.40001000", Longitude = "27.70027000" }
                    }
                },

                new()
                {
                    Id = 10,
                    Name = "Thaba-Tseka",
                    StateCode = "",
                    Latitude = "-29.51518320",
                    Longitude = "28.60361790",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Thaba-Tseka", Latitude = "-29.52204000", Longitude = "28.60840000" }
                    }
                }
            }
        };
    }
}
