// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Liberia
    {
        public static Country Data { get; } = new()
        {
            Id = 122,
            Name = "Liberia",
            Iso3 = "LBR",
            Iso2 = "LR",
            NumericCode = "430",
            PhoneCode = "231",
            Capital = "Monrovia",
            Currency = "LRD",
            CurrencyName = "Liberian dollar",
            CurrencySymbol = "$",
            Tld = ".lr",
            Native = "Liberia",
            Region = "Africa",
            RegionId = 1,
            Subregion = "Western Africa",
            SubregionId = 3,
            Nationality = "Liberian",
            Latitude = "6.50000000",
            Longitude = "-9.50000000",
            Emoji = "🇱🇷",
            EmojiU = "U+1F1F1 U+1F1F7",
            Timezones = new()
            {
                new() { ZoneName = "Africa/Monrovia", GmtOffset = 0, GmtOffsetName = "UTC±00", Abbreviation = "GMT", TzName = "Greenwich Mean Time" }
            },
            Translations = new()
            {
                ["br"] = "Liberia",
                ["ko"] = "라이베리아",
                ["pt-BR"] = "Libéria",
                ["pt"] = "Libéria",
                ["nl"] = "Liberia",
                ["hr"] = "Liberija",
                ["fa"] = "لیبریا",
                ["de"] = "Liberia",
                ["es"] = "Liberia",
                ["fr"] = "Liberia",
                ["ja"] = "リベリア",
                ["it"] = "Liberia",
                ["zh-CN"] = "利比里亚",
                ["tr"] = "Liberya",
                ["ru"] = "Либерия",
                ["uk"] = "Ліберія",
                ["pl"] = "Liberia",
                ["hi"] = "लाइबेरिया",
                ["ar"] = "ليبيريا"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Bomi",
                    StateCode = "",
                    Latitude = "6.71778560",
                    Longitude = "-10.78817660",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Tubmanburg", Latitude = "6.87064000", Longitude = "-10.82110000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Bong",
                    StateCode = "",
                    Latitude = "6.96221950",
                    Longitude = "-9.71344590",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Gbarnga", Latitude = "6.99543000", Longitude = "-9.47122000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Gbarpolu",
                    StateCode = "",
                    Latitude = "7.26815640",
                    Longitude = "-10.38147710",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bopolu", Latitude = "7.06667000", Longitude = "-10.48750000" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Grand Bassa",
                    StateCode = "",
                    Latitude = "6.16406210",
                    Longitude = "-9.89566900",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Buchanan", Latitude = "5.87693000", Longitude = "-10.04964000" }
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Grand Cape Mount",
                    StateCode = "",
                    Latitude = "7.04962060",
                    Longitude = "-11.12984300",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Robertsport", Latitude = "6.75329000", Longitude = "-11.36710000" }
                    }
                },

                new()
                {
                    Id = 6,
                    Name = "Grand Gedeh",
                    StateCode = "",
                    Latitude = "5.81615330",
                    Longitude = "-8.09955370",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Zwedru", Latitude = "6.06846000", Longitude = "-8.13559000" }
                    }
                },

                new()
                {
                    Id = 7,
                    Name = "Grand Kru",
                    StateCode = "",
                    Latitude = "4.84932000",
                    Longitude = "-8.33088450",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Barclayville", Latitude = "4.67443000", Longitude = "-8.23306000" }
                    }
                },

                new()
                {
                    Id = 8,
                    Name = "Lofa",
                    StateCode = "",
                    Latitude = "7.88240460",
                    Longitude = "-9.97602970",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Voinjama", Latitude = "8.42194000", Longitude = "-9.74778000" }
                    }
                },

                new()
                {
                    Id = 9,
                    Name = "Margibi",
                    StateCode = "",
                    Latitude = "6.60536760",
                    Longitude = "-10.17584290",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Kakata", Latitude = "6.53104000", Longitude = "-10.35368000" }
                    }
                },

                new()
                {
                    Id = 10,
                    Name = "Maryland",
                    StateCode = "",
                    Latitude = "4.63553760",
                    Longitude = "-7.72816690",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Harper", Latitude = "4.37820000", Longitude = "-7.71081000" }
                    }
                },

                new()
                {
                    Id = 11,
                    Name = "Montserrado",
                    StateCode = "",
                    Latitude = "6.40955370",
                    Longitude = "-10.60594030",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bensonville", Latitude = "6.44716000", Longitude = "-10.61283000" },
                        new() { Id = 2, Name = "Monrovia", Latitude = "6.30054000", Longitude = "-10.79690000" }
                    }
                },

                new()
                {
                    Id = 12,
                    Name = "Nimba",
                    StateCode = "",
                    Latitude = "6.80888130",
                    Longitude = "-8.74614480",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ganta", Latitude = "7.30222000", Longitude = "-8.53083000" },
                        new() { Id = 2, Name = "New Yekepa", Latitude = "7.57944000", Longitude = "-8.53778000" },
                        new() { Id = 3, Name = "Sanniquellie", Latitude = "7.36215000", Longitude = "-8.71326000" }
                    }
                },

                new()
                {
                    Id = 13,
                    Name = "River Cess",
                    StateCode = "",
                    Latitude = "5.90873310",
                    Longitude = "-9.39382670",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Cestos City", Latitude = "5.45683000", Longitude = "-9.58167000" }
                    }
                },

                new()
                {
                    Id = 14,
                    Name = "River Gee",
                    StateCode = "",
                    Latitude = "5.26539030",
                    Longitude = "-7.88562030",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Fish Town", Latitude = "5.19739000", Longitude = "-7.87579000" }
                    }
                },

                new()
                {
                    Id = 15,
                    Name = "Sinoe",
                    StateCode = "",
                    Latitude = "5.32326930",
                    Longitude = "-8.84359550",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Greenville", Latitude = "5.01133000", Longitude = "-9.03880000" }
                    }
                }
            }
        };
    }
}
