// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Luxembourg
    {
        public static Country Data { get; } = new()
        {
            Id = 126,
            Name = "Luxembourg",
            Iso3 = "LUX",
            Iso2 = "LU",
            NumericCode = "442",
            PhoneCode = "352",
            Capital = "Luxembourg",
            Currency = "EUR",
            CurrencyName = "Euro",
            CurrencySymbol = "€",
            Tld = ".lu",
            Native = "Luxembourg",
            Region = "Europe",
            RegionId = 4,
            Subregion = "Western Europe",
            SubregionId = 17,
            Nationality = "Luxembourg, Luxembourgish",
            Latitude = "49.75000000",
            Longitude = "6.16666666",
            Emoji = "🇱🇺",
            EmojiU = "U+1F1F1 U+1F1FA",
            Timezones = new()
            {
                new() { ZoneName = "Europe/Luxembourg", GmtOffset = 3600, GmtOffsetName = "UTC+01:00", Abbreviation = "CET", TzName = "Central European Time" }
            },
            Translations = new()
            {
                { "ko" = "룩셈부르크" },
                { "pt-BR" = "Luxemburgo" }
                { "pt" = "Luxemburgo" }
                { "nl" = "Luxemburg" }
                { "hr" = "Luksemburg" }
                { "fa" = "لوکزامبورگ" }
                { "de" = "Luxemburg" }
                { "es" = "Luxemburgo" }
                { "fr" = "Luxembourg" }
                { "ja" = "ルクセンブルク" }
                { "it" = "Lussemburgo" }
                { "zh-CN" = "卢森堡" }
                { "tr" = "Lüksemburg" }
                { "ru" = "Люксембург" }
                { "uk" = "Люксембург" }
                { "pl" = "Luksemburg" }
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Capellen",
                    StateCode = "CA",
                    Latitude = "49.64039310",
                    Longitude = "5.95538460",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bascharage", Latitude = "49.56727000", Longitude = "5.90730000" },
                        new() { Id = 2, Name = "Bridel", Latitude = "49.65579000", Longitude = "6.07999000" },
                        new() { Id = 3, Name = "Capellen", Latitude = "49.64500000", Longitude = "5.99083000" },
                        new() { Id = 4, Name = "Clemency", Latitude = "49.59667000", Longitude = "5.87583000" },
                        new() { Id = 5, Name = "Dippach", Latitude = "49.58701000", Longitude = "5.98330000" },
                        new() { Id = 6, Name = "Eischen", Latitude = "49.68556000", Longitude = "5.87861000" },
                        new() { Id = 7, Name = "Garnich", Latitude = "49.61667000", Longitude = "5.95250000" },
                        new() { Id = 8, Name = "Hautcharage", Latitude = "49.57499000", Longitude = "5.90970000" },
                        new() { Id = 9, Name = "Hobscheid", Latitude = "49.68861000", Longitude = "5.91472000" },
                        new() { Id = 10, Name = "Käerjeng", Latitude = "49.58311000", Longitude = "5.89892000" },
                        new() { Id = 11, Name = "Kehlen", Latitude = "49.66833000", Longitude = "6.03583000" },
                        new() { Id = 12, Name = "Koerich", Latitude = "49.67000000", Longitude = "5.95000000" },
                        new() { Id = 13, Name = "Kopstal", Latitude = "49.66444000", Longitude = "6.07306000" },
                        new() { Id = 14, Name = "Mamer", Latitude = "49.62750000", Longitude = "6.02333000" },
                        new() { Id = 15, Name = "Schouweiler", Latitude = "49.58250000", Longitude = "5.95639000" },
                        new() { Id = 16, Name = "Septfontaines", Latitude = "49.70111000", Longitude = "5.96722000" },
                        new() { Id = 17, Name = "Steinfort", Latitude = "49.66139000", Longitude = "5.91917000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Clervaux",
                    StateCode = "CL",
                    Latitude = "50.05463130",
                    Longitude = "6.02858750",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Clervaux", Latitude = "50.05472000", Longitude = "6.03139000" },
                        new() { Id = 2, Name = "Hosingen", Latitude = "50.01218000", Longitude = "6.09089000" },
                        new() { Id = 3, Name = "Parc Hosingen", Latitude = "49.99744000", Longitude = "6.09067000" },
                        new() { Id = 4, Name = "Troisvierges", Latitude = "50.12111000", Longitude = "6.00028000" },
                        new() { Id = 5, Name = "Weiswampach", Latitude = "50.13722000", Longitude = "6.07500000" },
                        new() { Id = 6, Name = "Wincrange", Latitude = "50.05333000", Longitude = "5.91917000" }
                    }
                }

                new()
                {
                    Id = 3,
                    Name = "Diekirch",
                    StateCode = "DI",
                    Latitude = "49.86717840",
                    Longitude = "6.15956330",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bettendorf", Latitude = "49.87667000", Longitude = "6.21806000" },
                        new() { Id = 2, Name = "Bourscheid", Latitude = "49.90862000", Longitude = "6.06750000" },
                        new() { Id = 3, Name = "Commune de la Vallée de l’Ernz", Latitude = "49.82149000", Longitude = "6.21746000" },
                        new() { Id = 4, Name = "Diekirch", Latitude = "49.86778000", Longitude = "6.15583000" },
                        new() { Id = 5, Name = "Erpeldange", Latitude = "49.86472000", Longitude = "6.11472000" },
                        new() { Id = 6, Name = "Ettelbruck", Latitude = "49.84750000", Longitude = "6.10417000" },
                        new() { Id = 7, Name = "Feulen", Latitude = "49.85000000", Longitude = "6.01667000" },
                        new() { Id = 8, Name = "Medernach", Latitude = "49.80955000", Longitude = "6.21521000" },
                        new() { Id = 9, Name = "Mertzig", Latitude = "49.83389000", Longitude = "6.00750000" },
                        new() { Id = 10, Name = "Niederfeulen", Latitude = "49.85556000", Longitude = "6.04722000" },
                        new() { Id = 11, Name = "Reisdorf", Latitude = "49.86861000", Longitude = "6.26778000" },
                        new() { Id = 12, Name = "Schieren", Latitude = "49.83056000", Longitude = "6.09861000" },
                        new() { Id = 13, Name = "Warken", Latitude = "49.85918000", Longitude = "6.08415000" }
                    }
                }

                new()
                {
                    Id = 4,
                    Name = "Echternach",
                    StateCode = "EC",
                    Latitude = "49.81141330",
                    Longitude = "6.41756350",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Beaufort", Latitude = "49.83583000", Longitude = "6.29167000" },
                        new() { Id = 2, Name = "Bech", Latitude = "49.75260000", Longitude = "6.36379000" },
                        new() { Id = 3, Name = "Berdorf", Latitude = "49.82051000", Longitude = "6.34945000" },
                        new() { Id = 4, Name = "Consdorf", Latitude = "49.78018000", Longitude = "6.33950000" },
                        new() { Id = 5, Name = "Echternach", Latitude = "49.81212000", Longitude = "6.41846000" },
                        new() { Id = 6, Name = "Mompach", Latitude = "49.74611000", Longitude = "6.46500000" },
                        new() { Id = 7, Name = "Rosport", Latitude = "49.80470000", Longitude = "6.50532000" },
                        new() { Id = 8, Name = "Waldbillig", Latitude = "49.79636000", Longitude = "6.28431000" }
                    }
                }

                new()
                {
                    Id = 5,
                    Name = "Esch-sur-Alzette",
                    StateCode = "ES",
                    Latitude = "49.50088050",
                    Longitude = "5.98609250",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Aspelt", Latitude = "49.52278000", Longitude = "6.22472000" },
                        new() { Id = 2, Name = "Belvaux", Latitude = "49.51014000", Longitude = "5.92414000" },
                        new() { Id = 3, Name = "Bergem", Latitude = "49.52500000", Longitude = "6.04222000" },
                        new() { Id = 4, Name = "Bettembourg", Latitude = "49.51861000", Longitude = "6.10278000" },
                        new() { Id = 5, Name = "Crauthem", Latitude = "49.53556000", Longitude = "6.14694000" },
                        new() { Id = 6, Name = "Differdange", Latitude = "49.52417000", Longitude = "5.89139000" },
                        new() { Id = 7, Name = "Dudelange", Latitude = "49.48056000", Longitude = "6.08750000" },
                        new() { Id = 8, Name = "Esch-sur-Alzette", Latitude = "49.49583000", Longitude = "5.98056000" },
                        new() { Id = 9, Name = "Frisange", Latitude = "49.51616000", Longitude = "6.18858000" },
                        new() { Id = 10, Name = "Kayl", Latitude = "49.48917000", Longitude = "6.03972000" },
                        new() { Id = 11, Name = "Lamadelaine", Latitude = "49.54639000", Longitude = "5.85639000" },
                        new() { Id = 12, Name = "Leudelange", Latitude = "49.56833000", Longitude = "6.06528000" },
                        new() { Id = 13, Name = "Mondercange", Latitude = "49.53306000", Longitude = "5.98833000" },
                        new() { Id = 14, Name = "Niedercorn", Latitude = "49.53611000", Longitude = "5.89306000" },
                        new() { Id = 15, Name = "Obercorn", Latitude = "49.51361000", Longitude = "5.89611000" },
                        new() { Id = 16, Name = "Pétange", Latitude = "49.55833000", Longitude = "5.88056000" },
                        new() { Id = 17, Name = "Pontpierre", Latitude = "49.53639000", Longitude = "6.02944000" },
                        new() { Id = 18, Name = "Reckange-sur-Mess", Latitude = "49.56250000", Longitude = "6.00889000" },
                        new() { Id = 19, Name = "Rodange", Latitude = "49.54639000", Longitude = "5.84083000" },
                        new() { Id = 20, Name = "Roeser", Latitude = "49.53721000", Longitude = "6.14629000" },
                        new() { Id = 21, Name = "Rumelange", Latitude = "49.45964000", Longitude = "6.03089000" },
                        new() { Id = 22, Name = "Sanem", Latitude = "49.54806000", Longitude = "5.92889000" },
                        new() { Id = 23, Name = "Schifflange", Latitude = "49.50639000", Longitude = "6.01278000" },
                        new() { Id = 24, Name = "Soleuvre", Latitude = "49.52148000", Longitude = "5.93781000" },
                        new() { Id = 25, Name = "Tétange", Latitude = "49.47583000", Longitude = "6.04222000" }
                    }
                }

                new()
                {
                    Id = 6,
                    Name = "Grevenmacher",
                    StateCode = "G",
                    Latitude = "49.68085100",
                    Longitude = "6.44075240",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Betzdorf", Latitude = "49.68333000", Longitude = "6.35000000" },
                        new() { Id = 2, Name = "Biwer", Latitude = "49.70605000", Longitude = "6.37201000" },
                        new() { Id = 3, Name = "Flaxweiler", Latitude = "49.66602000", Longitude = "6.34321000" },
                        new() { Id = 4, Name = "Gonderange", Latitude = "49.69537000", Longitude = "6.24577000" },
                        new() { Id = 5, Name = "Grevenmacher", Latitude = "49.67751000", Longitude = "6.44022000" },
                        new() { Id = 6, Name = "Junglinster", Latitude = "49.70722000", Longitude = "6.25306000" },
                        new() { Id = 7, Name = "Manternach", Latitude = "49.70278000", Longitude = "6.42639000" },
                        new() { Id = 8, Name = "Mertert", Latitude = "49.70261000", Longitude = "6.47966000" },
                        new() { Id = 9, Name = "Wasserbillig", Latitude = "49.71534000", Longitude = "6.49861000" },
                        new() { Id = 10, Name = "Wormeldange", Latitude = "49.61114000", Longitude = "6.40546000" }
                    }
                }

                new()
                {
                    Id = 7,
                    Name = "Luxembourg ",
                    StateCode = "L",
                    Latitude = "49.59537060",
                    Longitude = "6.13331780",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Alzingen", Latitude = "49.56500000", Longitude = "6.16361000" },
                        new() { Id = 2, Name = "Béreldange", Latitude = "49.65507000", Longitude = "6.11874000" },
                        new() { Id = 3, Name = "Bertrange", Latitude = "49.61111000", Longitude = "6.05000000" },
                        new() { Id = 4, Name = "Contern", Latitude = "49.58194000", Longitude = "6.22667000" },
                        new() { Id = 5, Name = "Fentange", Latitude = "49.56278000", Longitude = "6.15389000" },
                        new() { Id = 6, Name = "Heisdorf", Latitude = "49.67207000", Longitude = "6.14202000" },
                        new() { Id = 7, Name = "Helmsange", Latitude = "49.65278000", Longitude = "6.14139000" },
                        new() { Id = 8, Name = "Hesperange", Latitude = "49.56806000", Longitude = "6.15139000" },
                        new() { Id = 9, Name = "Itzig", Latitude = "49.58769000", Longitude = "6.17065000" },
                        new() { Id = 10, Name = "Kirchberg", Latitude = "49.62389000", Longitude = "6.14944000" },
                        new() { Id = 11, Name = "Luxembourg", Latitude = "49.61167000", Longitude = "6.13000000" },
                        new() { Id = 12, Name = "Moutfort", Latitude = "49.58528000", Longitude = "6.25556000" },
                        new() { Id = 13, Name = "Müllendorf", Latitude = "49.68028000", Longitude = "6.13000000" },
                        new() { Id = 14, Name = "Niederanven", Latitude = "49.65196000", Longitude = "6.26199000" },
                        new() { Id = 15, Name = "Olm", Latitude = "49.65722000", Longitude = "6.00028000" },
                        new() { Id = 16, Name = "Sandweiler", Latitude = "49.61471000", Longitude = "6.22221000" },
                        new() { Id = 17, Name = "Schrassig", Latitude = "49.61014000", Longitude = "6.25903000" },
                        new() { Id = 18, Name = "Schuttrange", Latitude = "49.62056000", Longitude = "6.26861000" },
                        new() { Id = 19, Name = "Steinsel", Latitude = "49.67694000", Longitude = "6.12389000" },
                        new() { Id = 20, Name = "Strassen", Latitude = "49.62056000", Longitude = "6.07333000" },
                        new() { Id = 21, Name = "Walferdange", Latitude = "49.66321000", Longitude = "6.13224000" },
                        new() { Id = 22, Name = "Weiler-la-Tour", Latitude = "49.54083000", Longitude = "6.20083000" }
                    }
                }

                new()
                {
                    Id = 8,
                    Name = "Mersch",
                    StateCode = "ME",
                    Latitude = "49.75429060",
                    Longitude = "6.12921850",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bissen", Latitude = "49.78733000", Longitude = "6.06540000" },
                        new() { Id = 2, Name = "Boevange-sur-Attert", Latitude = "49.77256000", Longitude = "6.01532000" },
                        new() { Id = 3, Name = "Colmar", Latitude = "49.81028000", Longitude = "6.09722000" },
                        new() { Id = 4, Name = "Fischbach", Latitude = "49.74600000", Longitude = "6.18702000" },
                        new() { Id = 5, Name = "Heffingen", Latitude = "49.76907000", Longitude = "6.24049000" },
                        new() { Id = 6, Name = "Larochette", Latitude = "49.78362000", Longitude = "6.21891000" },
                        new() { Id = 7, Name = "Lintgen", Latitude = "49.72243000", Longitude = "6.13016000" },
                        new() { Id = 8, Name = "Lorentzweiler", Latitude = "49.70131000", Longitude = "6.14234000" },
                        new() { Id = 9, Name = "Mersch", Latitude = "49.74889000", Longitude = "6.10611000" },
                        new() { Id = 10, Name = "Nommern", Latitude = "49.78694000", Longitude = "6.17472000" },
                        new() { Id = 11, Name = "Rollingen", Latitude = "49.74167000", Longitude = "6.11444000" },
                        new() { Id = 12, Name = "Tuntange", Latitude = "49.71778000", Longitude = "6.01028000" }
                    }
                }

                new()
                {
                    Id = 9,
                    Name = "Redange",
                    StateCode = "RD",
                    Latitude = "49.76455000",
                    Longitude = "5.88948000",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Beckerich", Latitude = "49.73056000", Longitude = "5.88722000" },
                        new() { Id = 2, Name = "Bettborn", Latitude = "49.79528000", Longitude = "5.94111000" },
                        new() { Id = 3, Name = "Commune de Préizerdaul", Latitude = "49.80114000", Longitude = "5.93299000" },
                        new() { Id = 4, Name = "Ell", Latitude = "49.76389000", Longitude = "5.85722000" },
                        new() { Id = 5, Name = "Grosbous", Latitude = "49.82778000", Longitude = "5.96722000" },
                        new() { Id = 6, Name = "Rambrouch", Latitude = "49.83083000", Longitude = "5.84500000" },
                        new() { Id = 7, Name = "Redange-sur-Attert", Latitude = "49.76437000", Longitude = "5.88997000" },
                        new() { Id = 8, Name = "Saeul", Latitude = "49.72722000", Longitude = "5.98639000" },
                        new() { Id = 9, Name = "Useldange", Latitude = "49.76972000", Longitude = "5.98222000" },
                        new() { Id = 10, Name = "Vichten", Latitude = "49.80306000", Longitude = "6.00000000" },
                        new() { Id = 11, Name = "Wahl", Latitude = "49.83667000", Longitude = "5.90639000" }
                    }
                }

                new()
                {
                    Id = 10,
                    Name = "Remich",
                    StateCode = "RM",
                    Latitude = "49.54501700",
                    Longitude = "6.36742220",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bous", Latitude = "49.55389000", Longitude = "6.32917000" },
                        new() { Id = 2, Name = "Dalheim", Latitude = "49.54083000", Longitude = "6.25972000" },
                        new() { Id = 3, Name = "Lenningen", Latitude = "49.59861000", Longitude = "6.36806000" },
                        new() { Id = 4, Name = "Mondorf-les-Bains", Latitude = "49.50500000", Longitude = "6.28111000" },
                        new() { Id = 5, Name = "Remich", Latitude = "49.54500000", Longitude = "6.36694000" },
                        new() { Id = 6, Name = "Schengen", Latitude = "49.47000000", Longitude = "6.36200000" },
                        new() { Id = 7, Name = "Stadtbredimus", Latitude = "49.56278000", Longitude = "6.36444000" },
                        new() { Id = 8, Name = "Waldbredimus", Latitude = "49.55676000", Longitude = "6.28789000" }
                    }
                },

                new()
                {
                    Id = 11,
                    Name = "Vianden",
                    StateCode = "VD",
                    Latitude = "49.93419240",
                    Longitude = "6.20199170",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Putscheid", Latitude = "49.96083000", Longitude = "6.14306000" },
                        new() { Id = 2, Name = "Tandel", Latitude = "49.89750000", Longitude = "6.18333000" },
                        new() { Id = 3, Name = "Vianden", Latitude = "49.93500000", Longitude = "6.20889000" }
                    }
                },

                new()
                {
                    Id = 12,
                    Name = "Wiltz",
                    StateCode = "WI",
                    Latitude = "49.96622000",
                    Longitude = "5.93243060",
                    Type = "canton",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bavigne", Latitude = "49.92194000", Longitude = "5.84944000" },
                        new() { Id = 2, Name = "Boulaide", Latitude = "49.88778000", Longitude = "5.81639000" },
                        new() { Id = 3, Name = "Esch-sur-Sûre", Latitude = "49.91139000", Longitude = "5.93639000" },
                        new() { Id = 4, Name = "Goesdorf", Latitude = "49.92131000", Longitude = "5.96601000" },
                        new() { Id = 5, Name = "Kiischpelt", Latitude = "49.97835000", Longitude = "6.00760000" },
                        new() { Id = 6, Name = "Lac de la Haute-Sûre", Latitude = "49.91667000", Longitude = "5.83333000" },
                        new() { Id = 7, Name = "Wiltz", Latitude = "49.96547000", Longitude = "5.93390000" },
                        new() { Id = 8, Name = "Wilwerwiltz", Latitude = "49.98889000", Longitude = "5.99917000" },
                        new() { Id = 9, Name = "Winseler", Latitude = "49.96778000", Longitude = "5.89028000" }
                    }
                }
            }
        };
    }
}
