// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Micronesia
    {
        public static Country Data { get; } = new()
        {
            Id = 141,
            Name = "Micronesia",
            Iso3 = "FSM",
            Iso2 = "FM",
            NumericCode = "583",
            PhoneCode = "691",
            Capital = "Palikir",
            Currency = "USD",
            CurrencyName = "United States dollar",
            CurrencySymbol = "$",
            Tld = ".fm",
            Native = "Micronesia",
            Region = "Oceania",
            RegionId = 5,
            Subregion = "Micronesia",
            SubregionId = 21,
            Nationality = "Micronesian",
            Latitude = "6.91666666",
            Longitude = "158.25000000",
            Emoji = "🇫🇲",
            EmojiU = "U+1F1EB U+1F1F2",
            Timezones = new()
            {
                new() { ZoneName = "Pacific/Chuuk", GmtOffset = 36000, GmtOffsetName = "UTC+10:00", Abbreviation = "CHUT", TzName = "Chuuk Time" },
                new() { ZoneName = "Pacific/Kosrae", GmtOffset = 39600, GmtOffsetName = "UTC+11:00", Abbreviation = "KOST", TzName = "Kosrae Time" },
                new() { ZoneName = "Pacific/Pohnpei", GmtOffset = 39600, GmtOffsetName = "UTC+11:00", Abbreviation = "PONT", TzName = "Pohnpei Standard Time" }
            },
            Translations = new()
            {
                { "ko" = "미크로네시아 연방" },
                { "pt-BR" = "Micronésia" }
                { "pt" = "Micronésia" }
                { "nl" = "Micronesië" }
                { "hr" = "Mikronezija" }
                { "fa" = "ایالات فدرال میکرونزی" }
                { "de" = "Mikronesien" }
                { "es" = "Micronesia" }
                { "fr" = "Micronésie" }
                { "ja" = "ミクロネシア連邦" }
                { "it" = "Micronesia" }
                { "zh-CN" = "密克罗尼西亚" }
                { "tr" = "Mikronezya" }
                { "ru" = "Микронезия" }
                { "uk" = "Мікронезія" }
                { "pl" = "Mikronezja" }
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Chuuk",
                    StateCode = "TRK",
                    Latitude = "7.13867590",
                    Longitude = "151.55930650",
                    Type = "state",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Eot Municipality", Latitude = "7.38540000", Longitude = "151.73920000" },
                        new() { Id = 2, Name = "Ettal Municipality", Latitude = "5.59200000", Longitude = "153.56000000" },
                        new() { Id = 3, Name = "Fananu Municipality", Latitude = "8.55811000", Longitude = "151.90822000" },
                        new() { Id = 4, Name = "Fanapanges Municipality", Latitude = "7.35300000", Longitude = "151.66760000" },
                        new() { Id = 5, Name = "Fefen Municipality", Latitude = "7.35300000", Longitude = "151.83100000" },
                        new() { Id = 6, Name = "Fonoton Municipality", Latitude = "7.48600000", Longitude = "151.87940000" },
                        new() { Id = 7, Name = "Houk Municipality", Latitude = "6.68300000", Longitude = "149.30000000" },
                        new() { Id = 8, Name = "Kuttu Municipality", Latitude = "5.45300000", Longitude = "153.45600000" },
                        new() { Id = 9, Name = "Lekinioch Municipality", Latitude = "5.50700000", Longitude = "153.81900000" },
                        new() { Id = 10, Name = "Losap Municipality", Latitude = "6.89400000", Longitude = "152.73900000" },
                        new() { Id = 11, Name = "Makur Municipality", Latitude = "8.98500000", Longitude = "150.12600000" },
                        new() { Id = 12, Name = "Moch Municipality", Latitude = "5.49180000", Longitude = "153.53850000" },
                        new() { Id = 13, Name = "Murilo", Latitude = "8.69242000", Longitude = "152.33934000" },
                        new() { Id = 14, Name = "Murilo Municipality", Latitude = "8.69200000", Longitude = "152.34200000" },
                        new() { Id = 15, Name = "Namoluk Municipality", Latitude = "5.91500000", Longitude = "153.13600000" },
                        new() { Id = 16, Name = "Nema", Latitude = "6.98922000", Longitude = "152.57377000" },
                        new() { Id = 17, Name = "Nema Municipality", Latitude = "6.99300000", Longitude = "152.57400000" },
                        new() { Id = 18, Name = "Nomwin Municipality", Latitude = "8.43000000", Longitude = "151.74500000" },
                        new() { Id = 19, Name = "Oneop Municipality", Latitude = "5.50660000", Longitude = "153.70900000" },
                        new() { Id = 20, Name = "Onou Municipality", Latitude = "8.79900000", Longitude = "150.29000000" },
                        new() { Id = 21, Name = "Onoun Municipality", Latitude = "8.57500000", Longitude = "149.68550000" },
                        new() { Id = 22, Name = "Paata-Tupunion Municipality", Latitude = "7.37600000", Longitude = "151.58300000" },
                        new() { Id = 23, Name = "Parem Municipality", Latitude = "7.36200000", Longitude = "151.78900000" },
                        new() { Id = 24, Name = "Piherarh Municipality", Latitude = "8.56900000", Longitude = "150.41800000" },
                        new() { Id = 25, Name = "Piis-Emwar Municipality", Latitude = "6.83400000", Longitude = "152.70000000" },
                        new() { Id = 26, Name = "Piis-Panewu Municipality", Latitude = "7.67800000", Longitude = "151.76340000" },
                        new() { Id = 27, Name = "Pollap Municipality", Latitude = "7.63971000", Longitude = "149.43011000" },
                        new() { Id = 28, Name = "Polowat Municipality", Latitude = "7.35500000", Longitude = "149.18200000" },
                        new() { Id = 29, Name = "Pwene Municipality", Latitude = "7.33700000", Longitude = "151.58400000" },
                        new() { Id = 30, Name = "Ramanum Municipality", Latitude = "7.41350000", Longitude = "151.66460000" },
                        new() { Id = 31, Name = "Ruo Municipality", Latitude = "8.60900000", Longitude = "152.24400000" },
                        new() { Id = 32, Name = "Satowan Municipality", Latitude = "5.33400000", Longitude = "153.73650000" },
                        new() { Id = 33, Name = "Siis Municipality", Latitude = "7.29500000", Longitude = "151.82460000" },
                        new() { Id = 34, Name = "Ta Municipality", Latitude = "5.28420000", Longitude = "153.64650000" },
                        new() { Id = 35, Name = "Tamatam Municipality", Latitude = "7.53898000", Longitude = "149.41175000" },
                        new() { Id = 36, Name = "Tolensom Municipality", Latitude = "7.33300000", Longitude = "151.62300000" },
                        new() { Id = 37, Name = "Tonoas Municipality", Latitude = "7.38100000", Longitude = "151.89000000" },
                        new() { Id = 38, Name = "Udot-Fonuweisom Municipality", Latitude = "7.38900000", Longitude = "151.70800000" },
                        new() { Id = 39, Name = "Uman-Fonuweisom Municipality", Latitude = "7.29900000", Longitude = "151.87700000" },
                        new() { Id = 40, Name = "Unanu Municipality", Latitude = "8.75000000", Longitude = "150.33950000" },
                        new() { Id = 41, Name = "Weno", Latitude = "7.44648000", Longitude = "151.84135000" },
                        new() { Id = 42, Name = "Weno Municipality", Latitude = "7.44000000", Longitude = "151.88100000" },
                        new() { Id = 43, Name = "Wonei Municipality", Latitude = "7.38700000", Longitude = "151.60100000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Kosrae",
                    StateCode = "KSA",
                    Latitude = "5.30956180",
                    Longitude = "162.98148770",
                    Type = "state",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Lelu Municipality", Latitude = "5.34865000", Longitude = "163.01917000" },
                        new() { Id = 2, Name = "Malem Municipality", Latitude = "5.27507000", Longitude = "163.01685000" },
                        new() { Id = 3, Name = "Tafunsak Municipality", Latitude = "5.34993000", Longitude = "162.96965000" },
                        new() { Id = 4, Name = "Tofol", Latitude = "5.32479000", Longitude = "163.00781000" },
                        new() { Id = 5, Name = "Utwe Municipality", Latitude = "5.27511000", Longitude = "162.95617000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Pohnpei",
                    StateCode = "PNI",
                    Latitude = "6.85412540",
                    Longitude = "158.26238220",
                    Type = "state",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Kitti Municipality", Latitude = "6.82490000", Longitude = "158.16081000" },
                        new() { Id = 2, Name = "Kolonia", Latitude = "6.96400000", Longitude = "158.20620000" },
                        new() { Id = 3, Name = "Kolonia Municipality", Latitude = "6.96400000", Longitude = "158.20580000" },
                        new() { Id = 4, Name = "Kolonia Town", Latitude = "6.96400000", Longitude = "158.20600000" },
                        new() { Id = 5, Name = "Madolenihm Municipality", Latitude = "6.86759000", Longitude = "158.31277000" },
                        new() { Id = 6, Name = "Mokil Municipality", Latitude = "6.68916000", Longitude = "159.76610000" },
                        new() { Id = 7, Name = "Nett Municipality", Latitude = "6.95152000", Longitude = "158.22437000" },
                        new() { Id = 8, Name = "Ngatik", Latitude = "5.78849000", Longitude = "157.15954000" },
                        new() { Id = 9, Name = "Nukuoro Municipality", Latitude = "3.84100000", Longitude = "154.93000000" },
                        new() { Id = 10, Name = "Palikir - National Government Center", Latitude = "6.92477000", Longitude = "158.16109000" },
                        new() { Id = 11, Name = "Pingelap Municipality", Latitude = "6.20908000", Longitude = "160.71033000" },
                        new() { Id = 12, Name = "Sapwuahfik Municipality", Latitude = "5.81500000", Longitude = "157.28000000" },
                        new() { Id = 13, Name = "Sokehs Municipality", Latitude = "6.93273000", Longitude = "158.14270000" },
                        new() { Id = 14, Name = "U Municipality", Latitude = "6.94972000", Longitude = "158.27361000" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Yap",
                    StateCode = "YAP",
                    Latitude = "8.67164900",
                    Longitude = "142.84393350",
                    Type = "state",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Colonia", Latitude = "9.51638000", Longitude = "138.12167000" },
                        new() { Id = 2, Name = "Dalipebinaw Municipality", Latitude = "9.52229000", Longitude = "138.08540000" },
                        new() { Id = 3, Name = "Fais", Latitude = "9.76600000", Longitude = "140.52000000" },
                        new() { Id = 4, Name = "Fais Municipality", Latitude = "9.76600000", Longitude = "140.51900000" },
                        new() { Id = 5, Name = "Fanif Municipality", Latitude = "9.56056000", Longitude = "138.11333000" },
                        new() { Id = 6, Name = "Faraulep Municipality", Latitude = "8.58800000", Longitude = "144.50650000" },
                        new() { Id = 7, Name = "Gagil Municipality", Latitude = "9.54722000", Longitude = "138.19028000" },
                        new() { Id = 8, Name = "Gilman Municipality", Latitude = "9.44611000", Longitude = "138.06389000" },
                        new() { Id = 9, Name = "Kanifay Municipality", Latitude = "9.46735000", Longitude = "138.05935000" },
                        new() { Id = 10, Name = "Lamotrek Municipality", Latitude = "7.49100000", Longitude = "146.30300000" },
                        new() { Id = 11, Name = "Maap Municipality", Latitude = "9.58975000", Longitude = "138.17119000" },
                        new() { Id = 12, Name = "Ngulu Municipality", Latitude = "8.45000000", Longitude = "137.48100000" },
                        new() { Id = 13, Name = "Rull Municipality", Latitude = "9.50773000", Longitude = "138.11540000" },
                        new() { Id = 14, Name = "Rumung Municipality", Latitude = "9.62428000", Longitude = "138.15745000" },
                        new() { Id = 15, Name = "Satawal Municipality", Latitude = "7.38200000", Longitude = "147.03180000" },
                        new() { Id = 16, Name = "Tomil Municipality", Latitude = "9.52517000", Longitude = "138.15488000" },
                        new() { Id = 17, Name = "Ulithi Municipality", Latitude = "9.90000000", Longitude = "139.60000000" },
                        new() { Id = 18, Name = "Weloy Municipality", Latitude = "9.52712000", Longitude = "138.11909000" },
                        new() { Id = 19, Name = "Woleai Municipality", Latitude = "7.34500000", Longitude = "143.85700000" }
                    }
                }
            }
        };
    }
}
