// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Mongolia
    {
        public static Country Data { get; } = new()
        {
            Id = 144,
            Name = "Mongolia",
            Iso3 = "MNG",
            Iso2 = "MN",
            NumericCode = "496",
            PhoneCode = "976",
            Capital = "Ulan Bator",
            Currency = "MNT",
            CurrencyName = "Mongolian tögrög",
            CurrencySymbol = "₮",
            Tld = ".mn",
            Native = "Монгол улс",
            Region = "Asia",
            RegionId = 3,
            Subregion = "Eastern Asia",
            SubregionId = 12,
            Nationality = "Mongolian",
            Latitude = "46.00000000",
            Longitude = "105.00000000",
            Emoji = "🇲🇳",
            EmojiU = "U+1F1F2 U+1F1F3",
            Timezones = new()
            {
                new() { ZoneName = "Asia/Choibalsan", GmtOffset = 28800, GmtOffsetName = "UTC+08:00", Abbreviation = "CHOT", TzName = "Choibalsan Standard Time" },
                new() { ZoneName = "Asia/Hovd", GmtOffset = 25200, GmtOffsetName = "UTC+07:00", Abbreviation = "HOVT", TzName = "Hovd Time" },
                new() { ZoneName = "Asia/Ulaanbaatar", GmtOffset = 28800, GmtOffsetName = "UTC+08:00", Abbreviation = "ULAT", TzName = "Ulaanbaatar Standard Time" }
            },
            Translations = new()
            {
                ["br"] = "Mongolia",
                ["ko"] = "몽골",
                ["pt-BR"] = "Mongólia",
                ["pt"] = "Mongólia",
                ["nl"] = "Mongolië",
                ["hr"] = "Mongolija",
                ["fa"] = "مغولستان",
                ["de"] = "Mongolei",
                ["es"] = "Mongolia",
                ["fr"] = "Mongolie",
                ["ja"] = "モンゴル",
                ["it"] = "Mongolia",
                ["zh-CN"] = "蒙古",
                ["tr"] = "Moğolistan",
                ["ru"] = "Монголия",
                ["uk"] = "Монголія",
                ["pl"] = "Mongolia",
                ["hi"] = "मंगोलिया",
                ["ar"] = "منغوليا"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Arkhangai",
                    StateCode = "",
                    Latitude = "47.86264600",
                    Longitude = "101.03162830",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Tsetserleg", Latitude = "47.47500000", Longitude = "101.45417000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Bayan-Ölgii",
                    StateCode = "",
                    Latitude = "48.54700830",
                    Longitude = "89.85493580",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Altay", Latitude = "48.29359000", Longitude = "89.51488000" },
                        new() { Id = 2, Name = "Ölgii", Latitude = "48.96833000", Longitude = "89.96250000" },
                        new() { Id = 3, Name = "Tsengel", Latitude = "48.94314000", Longitude = "89.14358000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Bayankhongor",
                    StateCode = "",
                    Latitude = "45.23809370",
                    Longitude = "99.51467990",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bayanhongor", Latitude = "46.19444000", Longitude = "100.71806000" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Bulgan",
                    StateCode = "",
                    Latitude = "48.95214380",
                    Longitude = "103.39655910",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bulgan", Latitude = "48.81250000", Longitude = "103.53472000" }
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Darkhan-Uul",
                    StateCode = "",
                    Latitude = "49.37672910",
                    Longitude = "106.29013840",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Darhan", Latitude = "49.48667000", Longitude = "105.92278000" }
                    }
                },

                new()
                {
                    Id = 6,
                    Name = "Dornod",
                    StateCode = "",
                    Latitude = "47.67727810",
                    Longitude = "115.21771550",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Choibalsan", Latitude = "48.07257000", Longitude = "114.53264000" },
                        new() { Id = 2, Name = "Ereencav", Latitude = "49.88070000", Longitude = "115.72526000" }
                    }
                },

                new()
                {
                    Id = 7,
                    Name = "Dornogovi",
                    StateCode = "",
                    Latitude = "44.41796370",
                    Longitude = "109.77837530",
                    Type = "province",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 8,
                    Name = "Dundgovi",
                    StateCode = "",
                    Latitude = "45.51867220",
                    Longitude = "106.26115620",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Mandalgovi", Latitude = "45.76250000", Longitude = "106.27083000" }
                    }
                },

                new()
                {
                    Id = 9,
                    Name = "Govi-Altai",
                    StateCode = "",
                    Latitude = "45.34631390",
                    Longitude = "95.93258060",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Altai", Latitude = "46.37222000", Longitude = "96.25833000" }
                    }
                },

                new()
                {
                    Id = 10,
                    Name = "Govisümber",
                    StateCode = "",
                    Latitude = "46.46108270",
                    Longitude = "108.51731010",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Choyr", Latitude = "46.36111000", Longitude = "108.36111000" }
                    }
                },

                new()
                {
                    Id = 11,
                    Name = "Khentii",
                    StateCode = "",
                    Latitude = "47.88598100",
                    Longitude = "110.42010430",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Undurkhaan", Latitude = "47.31944000", Longitude = "110.65556000" }
                    }
                },

                new()
                {
                    Id = 12,
                    Name = "Khovd",
                    StateCode = "",
                    Latitude = "46.89979770",
                    Longitude = "92.29596510",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Khovd", Latitude = "48.00556000", Longitude = "91.64194000" },
                        new() { Id = 2, Name = "Möst", Latitude = "46.67712000", Longitude = "92.78521000" },
                        new() { Id = 3, Name = "Üyönch", Latitude = "46.04786000", Longitude = "92.02612000" }
                    }
                },

                new()
                {
                    Id = 13,
                    Name = "Khövsgöl",
                    StateCode = "",
                    Latitude = "50.22061960",
                    Longitude = "99.91704920",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Hanh", Latitude = "51.50265000", Longitude = "100.66395000" },
                        new() { Id = 2, Name = "Murun-kuren", Latitude = "49.63417000", Longitude = "100.16250000" },
                        new() { Id = 3, Name = "Tsengel", Latitude = "49.47833000", Longitude = "100.88944000" },
                        new() { Id = 4, Name = "Turt", Latitude = "51.50725000", Longitude = "100.66257000" }
                    }
                },

                new()
                {
                    Id = 14,
                    Name = "Ömnögovi",
                    StateCode = "",
                    Latitude = "43.28236300",
                    Longitude = "104.11338640",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Dalandzadgad", Latitude = "43.57083000", Longitude = "104.42500000" },
                        new() { Id = 2, Name = "Hanhongor", Latitude = "43.77345000", Longitude = "104.47998000" },
                        new() { Id = 3, Name = "Nomgon Sum", Latitude = "42.41462000", Longitude = "105.05640000" }
                    }
                },

                new()
                {
                    Id = 15,
                    Name = "Orkhon",
                    StateCode = "",
                    Latitude = "49.02437440",
                    Longitude = "104.29988630",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Erdenet", Latitude = "49.03333000", Longitude = "104.08333000" }
                    }
                },

                new()
                {
                    Id = 16,
                    Name = "Övörkhangai",
                    StateCode = "",
                    Latitude = "45.82970390",
                    Longitude = "102.72377690",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Arvayheer", Latitude = "46.26389000", Longitude = "102.77500000" },
                        new() { Id = 2, Name = "Harhorin", Latitude = "47.19753000", Longitude = "102.82379000" },
                        new() { Id = 3, Name = "Hovd", Latitude = "44.67024000", Longitude = "102.17491000" },
                        new() { Id = 4, Name = "Kharkhorin", Latitude = "47.19245000", Longitude = "102.81349000" },
                        new() { Id = 5, Name = "Nariynteel", Latitude = "45.95950000", Longitude = "101.45977000" }
                    }
                },

                new()
                {
                    Id = 17,
                    Name = "Selenge",
                    StateCode = "",
                    Latitude = "49.39101360",
                    Longitude = "107.06290340",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Dzüünharaa", Latitude = "48.85229000", Longitude = "106.45786000" },
                        new() { Id = 2, Name = "Sühbaatar", Latitude = "50.23139000", Longitude = "106.20778000" }
                    }
                },

                new()
                {
                    Id = 18,
                    Name = "Sükhbaatar",
                    StateCode = "",
                    Latitude = "46.20934170",
                    Longitude = "113.50771960",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Baruun-Urt", Latitude = "46.68056000", Longitude = "113.27917000" }
                    }
                },

                new()
                {
                    Id = 19,
                    Name = "Töv",
                    StateCode = "",
                    Latitude = "47.46925380",
                    Longitude = "106.55251610",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Centipede", Latitude = "47.70693000", Longitude = "106.95276000" },
                        new() { Id = 2, Name = "Dzuunmod", Latitude = "47.70694000", Longitude = "106.95278000" },
                        new() { Id = 3, Name = "Möngönmorĭt", Latitude = "48.19504000", Longitude = "108.48295000" },
                        new() { Id = 4, Name = "Ulaanhudag", Latitude = "47.33333000", Longitude = "104.50000000" },
                        new() { Id = 5, Name = "Ulan Bator", Latitude = "47.89176240", Longitude = "106.73706000" }
                    }
                },

                new()
                {
                    Id = 20,
                    Name = "Ulaanbaatar",
                    StateCode = "",
                    Latitude = "47.91846760",
                    Longitude = "106.91770160",
                    Type = "capital city",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ulaanbaatar", Latitude = "47.89153170", Longitude = "106.73672220" }
                    }
                },

                new()
                {
                    Id = 21,
                    Name = "Uvs",
                    StateCode = "",
                    Latitude = "49.63138870",
                    Longitude = "92.95581860",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ulaangom", Latitude = "49.98111000", Longitude = "92.06667000" }
                    }
                },

                new()
                {
                    Id = 22,
                    Name = "Zavkhan",
                    StateCode = "",
                    Latitude = "48.31333550",
                    Longitude = "96.28505060",
                    Type = "province",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Uliastay", Latitude = "47.74167000", Longitude = "96.84444000" }
                    }
                }
            }
        };
    }
}
