// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Namibia
    {
        public static Country Data { get; } = new()
        {
            Id = 150,
            Name = "Namibia",
            Iso3 = "NAM",
            Iso2 = "NA",
            NumericCode = "516",
            PhoneCode = "264",
            Capital = "Windhoek",
            Currency = "NAD",
            CurrencyName = "Namibian dollar",
            CurrencySymbol = "$",
            Tld = ".na",
            Native = "Namibia",
            Region = "Africa",
            RegionId = 1,
            Subregion = "Southern Africa",
            SubregionId = 5,
            Nationality = "Namibian",
            Latitude = "-22.00000000",
            Longitude = "17.00000000",
            Emoji = "🇳🇦",
            EmojiU = "U+1F1F3 U+1F1E6",
            Timezones = new()
            {
                new() { ZoneName = "Africa/Windhoek", GmtOffset = 7200, GmtOffsetName = "UTC+02:00", Abbreviation = "WAST", TzName = "West Africa Summer Time" }
            },
            Translations = new()
            {
                ["br"] = "Namibia",
                ["ko"] = "나미비아",
                ["pt-BR"] = "Namíbia",
                ["pt"] = "Namíbia",
                ["nl"] = "Namibië",
                ["hr"] = "Namibija",
                ["fa"] = "نامیبیا",
                ["de"] = "Namibia",
                ["es"] = "Namibia",
                ["fr"] = "Namibie",
                ["ja"] = "ナミビア",
                ["it"] = "Namibia",
                ["zh-CN"] = "纳米比亚",
                ["tr"] = "Namibya",
                ["ru"] = "Намибия",
                ["uk"] = "Намібія",
                ["pl"] = "Namibia",
                ["hi"] = "नामिबिया",
                ["ar"] = "ناميبيا"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Erongo",
                    StateCode = "",
                    Latitude = "-22.02781470",
                    Longitude = "15.38935800",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Arandis", Latitude = "-22.41667000", Longitude = "14.96667000" },
                        new() { Id = 2, Name = "Hentiesbaai", Latitude = "-22.11667000", Longitude = "14.28333000" },
                        new() { Id = 3, Name = "Karibib", Latitude = "-21.93333000", Longitude = "15.83333000" },
                        new() { Id = 4, Name = "Omaruru", Latitude = "-21.43333000", Longitude = "15.93333000" },
                        new() { Id = 5, Name = "Otjimbingwe", Latitude = "-22.35000000", Longitude = "16.13333000" },
                        new() { Id = 6, Name = "Swakopmund", Latitude = "-22.67842000", Longitude = "14.52663000" },
                        new() { Id = 7, Name = "Swakopmund Constituency", Latitude = "-22.63199000", Longitude = "14.60119000" },
                        new() { Id = 8, Name = "Usakos", Latitude = "-22.00000000", Longitude = "15.60000000" },
                        new() { Id = 9, Name = "Walvis Bay", Latitude = "-22.95750000", Longitude = "14.50528000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Hardap",
                    StateCode = "",
                    Latitude = "-24.41409440",
                    Longitude = "17.41340510",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Aranos", Latitude = "-24.13333000", Longitude = "19.11667000" },
                        new() { Id = 2, Name = "Hoachanas", Latitude = "-23.91667000", Longitude = "18.05000000" },
                        new() { Id = 3, Name = "Maltahöhe", Latitude = "-24.83333000", Longitude = "16.98333000" },
                        new() { Id = 4, Name = "Mariental", Latitude = "-24.63333000", Longitude = "17.96667000" },
                        new() { Id = 5, Name = "Rehoboth", Latitude = "-23.31700000", Longitude = "17.09000000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Karas",
                    StateCode = "",
                    Latitude = "-26.87520940",
                    Longitude = "17.76348180",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bethanie", Latitude = "-26.48333000", Longitude = "17.15000000" },
                        new() { Id = 2, Name = "Karasburg", Latitude = "-28.01667000", Longitude = "18.75000000" },
                        new() { Id = 3, Name = "Keetmanshoop", Latitude = "-26.58333000", Longitude = "18.13333000" },
                        new() { Id = 4, Name = "Lüderitz", Latitude = "-26.64807000", Longitude = "15.15383000" },
                        new() { Id = 5, Name = "Oranjemund", Latitude = "-28.55000000", Longitude = "16.43333000" },
                        new() { Id = 6, Name = "Tses", Latitude = "-25.88333000", Longitude = "18.00000000" },
                        new() { Id = 7, Name = "Warmbad", Latitude = "-28.45000000", Longitude = "18.73333000" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Kavango East",
                    StateCode = "",
                    Latitude = "-18.39823550",
                    Longitude = "20.72468000",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Rundu", Latitude = "-17.93333000", Longitude = "19.76667000" }
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Kavango West",
                    StateCode = "",
                    Latitude = "-18.25611100",
                    Longitude = "18.97020100",
                    Type = "region",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 6,
                    Name = "Khomas",
                    StateCode = "",
                    Latitude = "-22.90825530",
                    Longitude = "17.09198000",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Katutura", Latitude = "-22.52306000", Longitude = "17.06028000" },
                        new() { Id = 2, Name = "Windhoek", Latitude = "-22.55941000", Longitude = "17.08323000" }
                    }
                },

                new()
                {
                    Id = 7,
                    Name = "Kunene",
                    StateCode = "",
                    Latitude = "-19.67928090",
                    Longitude = "13.97565640",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Epupa Constituency", Latitude = "-17.00388000", Longitude = "13.24825000" },
                        new() { Id = 2, Name = "Khorixas", Latitude = "-20.36667000", Longitude = "14.96667000" },
                        new() { Id = 3, Name = "Khorixas Constituency", Latitude = "-20.36792000", Longitude = "14.95996000" },
                        new() { Id = 4, Name = "Opuwo", Latitude = "-18.06068000", Longitude = "13.83998000" },
                        new() { Id = 5, Name = "Opuwo Constituency", Latitude = "-18.54247000", Longitude = "13.51617000" },
                        new() { Id = 6, Name = "Outjo", Latitude = "-20.11667000", Longitude = "16.15000000" },
                        new() { Id = 7, Name = "Sesfontein Constituency", Latitude = "-19.56106000", Longitude = "13.76530000" }
                    }
                },

                new()
                {
                    Id = 8,
                    Name = "Ohangwena",
                    StateCode = "",
                    Latitude = "-17.58773690",
                    Longitude = "16.77379550",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Oshikango", Latitude = "-17.40000000", Longitude = "15.88333000" }
                    }
                },

                new()
                {
                    Id = 9,
                    Name = "Omaheke",
                    StateCode = "",
                    Latitude = "-21.90746760",
                    Longitude = "19.39296610",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Gobabis", Latitude = "-22.45000000", Longitude = "18.96667000" }
                    }
                },

                new()
                {
                    Id = 10,
                    Name = "Omusati",
                    StateCode = "",
                    Latitude = "-18.28623140",
                    Longitude = "14.88566790",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Okahao", Latitude = "-17.88758000", Longitude = "15.06677000" },
                        new() { Id = 2, Name = "Ongandjera", Latitude = "-17.88333000", Longitude = "15.06667000" },
                        new() { Id = 3, Name = "Outapi", Latitude = "-17.50000000", Longitude = "14.98333000" }
                    }
                },

                new()
                {
                    Id = 11,
                    Name = "Oshana",
                    StateCode = "",
                    Latitude = "-18.47023080",
                    Longitude = "15.74344190",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ondangwa", Latitude = "-17.91667000", Longitude = "15.95000000" },
                        new() { Id = 2, Name = "Ongwediva", Latitude = "-17.78333000", Longitude = "15.76667000" },
                        new() { Id = 3, Name = "Oshakati", Latitude = "-17.78833000", Longitude = "15.70436000" }
                    }
                },

                new()
                {
                    Id = 12,
                    Name = "Oshikoto",
                    StateCode = "",
                    Latitude = "-18.54640460",
                    Longitude = "17.10196060",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Omuthiya", Latitude = "-18.36463000", Longitude = "16.58146000" },
                        new() { Id = 2, Name = "Tsumeb", Latitude = "-19.23333000", Longitude = "17.71667000" }
                    }
                },

                new()
                {
                    Id = 13,
                    Name = "Otjozondjupa",
                    StateCode = "",
                    Latitude = "-19.94249620",
                    Longitude = "18.39588600",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Grootfontein", Latitude = "-19.56667000", Longitude = "18.11667000" },
                        new() { Id = 2, Name = "Okahandja", Latitude = "-21.98333000", Longitude = "16.91667000" },
                        new() { Id = 3, Name = "Okakarara", Latitude = "-20.58333000", Longitude = "17.43333000" },
                        new() { Id = 4, Name = "Otavi", Latitude = "-19.65000000", Longitude = "17.33333000" },
                        new() { Id = 5, Name = "Otjiwarongo", Latitude = "-20.46369000", Longitude = "16.64772000" }
                    }
                },

                new()
                {
                    Id = 14,
                    Name = "Zambezi",
                    StateCode = "",
                    Latitude = "-17.69129220",
                    Longitude = "24.13773710",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bagani", Latitude = "-18.11065000", Longitude = "21.61645000" },
                        new() { Id = 2, Name = "Katima Mulilo", Latitude = "-17.50000000", Longitude = "24.26667000" }
                    }
                }
            }
        };
    }
}
