// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Nauru
    {
        public static Country Data { get; } = new()
        {
            Id = 151,
            Name = "Nauru",
            Iso3 = "NRU",
            Iso2 = "NR",
            NumericCode = "520",
            PhoneCode = "674",
            Capital = "Yaren",
            Currency = "AUD",
            CurrencyName = "Australian dollar",
            CurrencySymbol = "$",
            Tld = ".nr",
            Native = "Nauru",
            Region = "Oceania",
            RegionId = 5,
            Subregion = "Micronesia",
            SubregionId = 21,
            Nationality = "Nauruan",
            Latitude = "-0.53333333",
            Longitude = "166.91666666",
            Emoji = "🇳🇷",
            EmojiU = "U+1F1F3 U+1F1F7",
            Timezones = new()
            {
                new() { ZoneName = "Pacific/Nauru", GmtOffset = 43200, GmtOffsetName = "UTC+12:00", Abbreviation = "NRT", TzName = "Nauru Time" }
            },
            Translations = new()
            {
                ["br"] = "Nauru",
                ["ko"] = "나우루",
                ["pt-BR"] = "Nauru",
                ["pt"] = "Nauru",
                ["nl"] = "Nauru",
                ["hr"] = "Nauru",
                ["fa"] = "نائورو",
                ["de"] = "Nauru",
                ["es"] = "Nauru",
                ["fr"] = "Nauru",
                ["ja"] = "ナウル",
                ["it"] = "Nauru",
                ["zh-CN"] = "瑙鲁",
                ["tr"] = "Nauru",
                ["ru"] = "Науру",
                ["uk"] = "Науру",
                ["pl"] = "Nauru",
                ["hi"] = "नाउरू",
                ["ar"] = "ناورو"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Aiwo",
                    StateCode = "",
                    Latitude = "-0.53400120",
                    Longitude = "166.91388730",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Arijejen", Latitude = "-0.52545000", Longitude = "166.91247000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Anabar",
                    StateCode = "",
                    Latitude = "-0.51335170",
                    Longitude = "166.94846240",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Anabar", Latitude = "-0.50845000", Longitude = "166.95326000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Anetan",
                    StateCode = "",
                    Latitude = "-0.50643430",
                    Longitude = "166.94270060",
                    Type = "district",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Anibare",
                    StateCode = "",
                    Latitude = "-0.52947580",
                    Longitude = "166.95134320",
                    Type = "district",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Baiti",
                    StateCode = "",
                    Latitude = "-0.51043100",
                    Longitude = "166.92757440",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Baiti", Latitude = "-0.50803000", Longitude = "166.92945000" }
                    }
                },

                new()
                {
                    Id = 6,
                    Name = "Boe",
                    StateCode = "",
                    Latitude = "-0.54230030",
                    Longitude = "166.91606090",
                    Type = "district",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 7,
                    Name = "Buada",
                    StateCode = "",
                    Latitude = "-0.53287770",
                    Longitude = "166.92685410",
                    Type = "district",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 8,
                    Name = "Denigomodu",
                    StateCode = "",
                    Latitude = "-0.52479640",
                    Longitude = "166.91676890",
                    Type = "district",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 9,
                    Name = "Ewa",
                    StateCode = "",
                    Latitude = "-0.50872410",
                    Longitude = "166.93693840",
                    Type = "district",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 10,
                    Name = "Ijuw",
                    StateCode = "",
                    Latitude = "-0.52027670",
                    Longitude = "166.95710460",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Ijuw", Latitude = "-0.52100000", Longitude = "166.95813000" }
                    }
                },

                new()
                {
                    Id = 11,
                    Name = "Meneng",
                    StateCode = "",
                    Latitude = "-0.54672400",
                    Longitude = "166.93837900",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Menen", Latitude = "-0.54539000", Longitude = "166.94871000" }
                    }
                },

                new()
                {
                    Id = 12,
                    Name = "Nibok",
                    StateCode = "",
                    Latitude = "-0.51962080",
                    Longitude = "166.91893010",
                    Type = "district",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 13,
                    Name = "Uaboe",
                    StateCode = "",
                    Latitude = "-0.52022220",
                    Longitude = "166.93117610",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Uaboe", Latitude = "-0.51393000", Longitude = "166.92384000" }
                    }
                },

                new()
                {
                    Id = 14,
                    Name = "Yaren",
                    StateCode = "",
                    Latitude = "-0.54668570",
                    Longitude = "166.92109130",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Yaren", Latitude = "-0.55085000", Longitude = "166.92520000" }
                    }
                }
            }
        };
    }
}
