// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    internal static class SaoTomeAndPrincipe
    {
        public static Country Data { get; } = new()
        {
            Id = 192,
            Name = "Sao Tome and Principe",
            Iso3 = "STP",
            Iso2 = "ST",
            NumericCode = "678",
            PhoneCode = "239",
            Capital = "Sao Tome",
            Currency = "STN",
            CurrencyName = "Dobra",
            CurrencySymbol = "Db",
            Tld = ".st",
            Native = "São Tomé e Príncipe",
            Region = "Africa",
            RegionId = 1,
            Subregion = "Middle Africa",
            SubregionId = 2,
            Nationality = "Sao Tomean",
            Latitude = "1.00000000",
            Longitude = "7.00000000",
            Emoji = "🇸🇹",
            EmojiU = "U+1F1F8 U+1F1F9",
            Timezones = new()
            {
                new() { ZoneName = "Africa/Sao_Tome", GmtOffset = 0, GmtOffsetName = "UTC±00", Abbreviation = "GMT", TzName = "Greenwich Mean Time" }
            },
            Translations = new()
            {
                ["br"] = "São Tomé ha Príncipe",
                ["ko"] = "상투메 프린시페",
                ["pt-BR"] = "São Tomé e Príncipe",
                ["pt"] = "São Tomé e Príncipe",
                ["nl"] = "Sao Tomé en Principe",
                ["hr"] = "Sveti Toma i Princip",
                ["fa"] = "کواترو دو فرویرو",
                ["de"] = "São Tomé und Príncipe",
                ["es"] = "Santo Tomé y Príncipe",
                ["fr"] = "Sao Tomé-et-Principe",
                ["ja"] = "サントメ・プリンシペ",
                ["it"] = "São Tomé e Príncipe",
                ["zh-CN"] = "圣多美和普林西比",
                ["tr"] = "Sao Tome Ve Prinsipe",
                ["ru"] = "Сан-Томе и Принсипи",
                ["uk"] = "Сан-Томе і Принсіпі",
                ["pl"] = "Wyspy Świętego Tomasza i Książęca",
                ["hi"] = "साओ टोम और प्रिंसिप",
                ["ar"] = "ساو تومي وبرينسيبي"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Água Grande",
                    StateCode = "",
                    Latitude = "0.33019240",
                    Longitude = "6.73334300",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "São Tomé", Latitude = "0.33654000", Longitude = "6.72732000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Cantagalo",
                    StateCode = "",
                    Latitude = "0.21667000",
                    Longitude = "6.70000000",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Santana", Latitude = "0.25389000", Longitude = "6.73444000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Caué",
                    StateCode = "",
                    Latitude = "0.13415000",
                    Longitude = "6.63825000",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "São João dos Angolares", Latitude = "0.13720000", Longitude = "6.64972000" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Lemba",
                    StateCode = "",
                    Latitude = "0.22000000",
                    Longitude = "6.58000000",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Neves", Latitude = "0.36667000", Longitude = "6.55000000" }
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Lobata",
                    StateCode = "",
                    Latitude = "0.41000000",
                    Longitude = "6.61000000",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Guadalupe", Latitude = "0.38333000", Longitude = "6.61667000" }
                    }
                },

                new()
                {
                    Id = 6,
                    Name = "Mé-Zóchi",
                    StateCode = "",
                    Latitude = "0.30000000",
                    Longitude = "6.60000000",
                    Type = "district",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Trindade", Latitude = "0.29667000", Longitude = "6.68139000" }
                    }
                },

                new()
                {
                    Id = 7,
                    Name = "Príncipe",
                    StateCode = "",
                    Latitude = "1.61393810",
                    Longitude = "7.40569280",
                    Type = "autonomous region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Santo António", Latitude = "1.63943000", Longitude = "7.41951000" }
                    }
                }
            }
        };
    }
}
