// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    internal static class Slovakia
    {
        public static Country Data { get; } = new()
        {
            Id = 200,
            Name = "Slovakia",
            Iso3 = "SVK",
            Iso2 = "SK",
            NumericCode = "703",
            PhoneCode = "421",
            Capital = "Bratislava",
            Currency = "EUR",
            CurrencyName = "Euro",
            CurrencySymbol = "€",
            Tld = ".sk",
            Native = "Slovensko",
            Region = "Europe",
            RegionId = 4,
            Subregion = "Eastern Europe",
            SubregionId = 15,
            Nationality = "Slovak",
            Latitude = "48.66666666",
            Longitude = "19.50000000",
            Emoji = "🇸🇰",
            EmojiU = "U+1F1F8 U+1F1F0",
            Timezones = new()
            {
                new() { ZoneName = "Europe/Bratislava", GmtOffset = 3600, GmtOffsetName = "UTC+01:00", Abbreviation = "CET", TzName = "Central European Time" }
            },
            Translations = new()
            {
                ["br"] = "Slovakia",
                ["ko"] = "슬로바키아",
                ["pt-BR"] = "Eslováquia",
                ["pt"] = "Eslováquia",
                ["nl"] = "Slowakije",
                ["hr"] = "Slovačka",
                ["fa"] = "اسلواکی",
                ["de"] = "Slowakei",
                ["es"] = "República Eslovaca",
                ["fr"] = "Slovaquie",
                ["ja"] = "スロバキア",
                ["it"] = "Slovacchia",
                ["zh-CN"] = "斯洛伐克",
                ["tr"] = "Slovakya",
                ["ru"] = "Словакия",
                ["uk"] = "Словаччина",
                ["pl"] = "Słowacja",
                ["hi"] = "स्लोवाकिया",
                ["ar"] = "سلوفاكيا"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Banská Bystrica",
                    StateCode = "",
                    Latitude = "48.73838950",
                    Longitude = "19.15858050",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Banská Bystrica", Latitude = "48.73946000", Longitude = "19.15349000" },
                        new() { Id = 2, Name = "Banská Štiavnica", Latitude = "48.44858000", Longitude = "18.91003000" },
                        new() { Id = 3, Name = "Brezno", Latitude = "48.80431000", Longitude = "19.63631000" },
                        new() { Id = 4, Name = "Čierny Balog", Latitude = "48.74722000", Longitude = "19.65125000" },
                        new() { Id = 5, Name = "Detva", Latitude = "48.56082000", Longitude = "19.41954000" },
                        new() { Id = 6, Name = "Dudince", Latitude = "48.17135000", Longitude = "18.88782000" },
                        new() { Id = 7, Name = "Fiľakovo", Latitude = "48.26757000", Longitude = "19.82473000" },
                        new() { Id = 8, Name = "Hriňová", Latitude = "48.57787000", Longitude = "19.52574000" },
                        new() { Id = 9, Name = "HrochoťSlovakia", Latitude = "48.65567000", Longitude = "19.31284000" },
                        new() { Id = 10, Name = "Kováčová", Latitude = "48.60148000", Longitude = "19.10252000" },
                        new() { Id = 11, Name = "Kremnica", Latitude = "48.70519000", Longitude = "18.91834000" },
                        new() { Id = 12, Name = "Krupina", Latitude = "48.35540000", Longitude = "19.06474000" },
                        new() { Id = 13, Name = "Lučenec", Latitude = "48.33249000", Longitude = "19.66708000" },
                        new() { Id = 14, Name = "Nová Baňa", Latitude = "48.42305000", Longitude = "18.64037000" },
                        new() { Id = 15, Name = "Okres Banská Bystrica", Latitude = "48.73333000", Longitude = "19.15000000" },
                        new() { Id = 16, Name = "Okres Banská Štiavnica", Latitude = "48.44961000", Longitude = "18.90820000" },
                        new() { Id = 17, Name = "Okres Brezno", Latitude = "48.80000000", Longitude = "19.75000000" },
                        new() { Id = 18, Name = "Okres Detva", Latitude = "48.55985000", Longitude = "19.42044000" },
                        new() { Id = 19, Name = "Okres Krupina", Latitude = "48.35736000", Longitude = "19.06334000" },
                        new() { Id = 20, Name = "Okres Lučenec", Latitude = "48.33333000", Longitude = "19.66667000" },
                        new() { Id = 21, Name = "Okres Poltár", Latitude = "48.42895000", Longitude = "19.79488000" },
                        new() { Id = 22, Name = "Okres Revúca", Latitude = "48.68300000", Longitude = "20.11568000" },
                        new() { Id = 23, Name = "Okres Veľký Krtíš", Latitude = "48.20000000", Longitude = "19.35000000" },
                        new() { Id = 24, Name = "Okres Žarnovica", Latitude = "48.48438000", Longitude = "18.72076000" },
                        new() { Id = 25, Name = "Okres Žiar nad Hronom", Latitude = "48.58333000", Longitude = "18.86667000" },
                        new() { Id = 26, Name = "Okres Zvolen", Latitude = "48.58333000", Longitude = "19.13333000" },
                        new() { Id = 27, Name = "Poltár", Latitude = "48.43094000", Longitude = "19.79408000" },
                        new() { Id = 28, Name = "Revúca", Latitude = "48.68346000", Longitude = "20.11734000" },
                        new() { Id = 29, Name = "Rimavská Sobota", Latitude = "48.38284000", Longitude = "20.02239000" },
                        new() { Id = 30, Name = "Svätý Anton", Latitude = "48.41923000", Longitude = "18.94010000" },
                        new() { Id = 31, Name = "Tisovec", Latitude = "48.67738000", Longitude = "19.94364000" },
                        new() { Id = 32, Name = "Veľký Krtíš", Latitude = "48.21059000", Longitude = "19.35043000" },
                        new() { Id = 33, Name = "Žarnovica", Latitude = "48.48123000", Longitude = "18.71565000" },
                        new() { Id = 34, Name = "Žiar nad Hronom", Latitude = "48.59184000", Longitude = "18.84958000" },
                        new() { Id = 35, Name = "Zvolen", Latitude = "48.57442000", Longitude = "19.15324000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Bratislava",
                    StateCode = "",
                    Latitude = "48.15576690",
                    Longitude = "17.13142030",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bratislava", Latitude = "48.14816000", Longitude = "17.10674000" },
                        new() { Id = 2, Name = "Bratislava - Vajnory", Latitude = "48.20563000", Longitude = "17.20759000" },
                        new() { Id = 3, Name = "Dunajská Lužná", Latitude = "48.08347000", Longitude = "17.26072000" },
                        new() { Id = 4, Name = "Ivanka pri Dunaji", Latitude = "48.18675000", Longitude = "17.25540000" },
                        new() { Id = 5, Name = "Malacky", Latitude = "48.43604000", Longitude = "17.02188000" },
                        new() { Id = 6, Name = "Marianka", Latitude = "48.24903000", Longitude = "17.06400000" },
                        new() { Id = 7, Name = "Modra", Latitude = "48.33397000", Longitude = "17.30711000" },
                        new() { Id = 8, Name = "Okres Bratislava I", Latitude = "48.14653000", Longitude = "17.10584000" },
                        new() { Id = 9, Name = "Okres Bratislava II", Latitude = "48.15280000", Longitude = "17.17764000" },
                        new() { Id = 10, Name = "Okres Bratislava III", Latitude = "48.18543000", Longitude = "17.13790000" },
                        new() { Id = 11, Name = "Okres Bratislava IV", Latitude = "48.22787000", Longitude = "16.99722000" },
                        new() { Id = 12, Name = "Okres Bratislava V", Latitude = "48.11122000", Longitude = "17.09444000" },
                        new() { Id = 13, Name = "Okres Malacky", Latitude = "48.43458000", Longitude = "17.02166000" },
                        new() { Id = 14, Name = "Okres Pezinok", Latitude = "48.28785000", Longitude = "17.26799000" },
                        new() { Id = 15, Name = "Okres Senec", Latitude = "48.22187000", Longitude = "17.40328000" },
                        new() { Id = 16, Name = "Pezinok", Latitude = "48.28986000", Longitude = "17.26664000" },
                        new() { Id = 17, Name = "Senec", Latitude = "48.21951000", Longitude = "17.40043000" },
                        new() { Id = 18, Name = "Stupava", Latitude = "48.27474000", Longitude = "17.03173000" },
                        new() { Id = 19, Name = "Svätý Jur", Latitude = "48.25216000", Longitude = "17.21539000" },
                        new() { Id = 20, Name = "Vinosady", Latitude = "48.31142000", Longitude = "17.29042000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Košice",
                    StateCode = "",
                    Latitude = "48.71722720",
                    Longitude = "21.24967740",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Čierna nad Tisou", Latitude = "48.41704000", Longitude = "22.08865000" },
                        new() { Id = 2, Name = "Dobšiná", Latitude = "48.82073000", Longitude = "20.36988000" },
                        new() { Id = 3, Name = "Gelnica", Latitude = "48.85584000", Longitude = "20.93713000" },
                        new() { Id = 4, Name = "Kavečany", Latitude = "48.77592000", Longitude = "21.20587000" },
                        new() { Id = 5, Name = "Košice", Latitude = "48.71395000", Longitude = "21.25808000" },
                        new() { Id = 6, Name = "Košice I", Latitude = "48.72914000", Longitude = "21.25004000" },
                        new() { Id = 7, Name = "Košice II", Latitude = "48.69753000", Longitude = "21.22273000" },
                        new() { Id = 8, Name = "Košice III", Latitude = "48.73242000", Longitude = "21.29047000" },
                        new() { Id = 9, Name = "Košice IV", Latitude = "48.68691000", Longitude = "21.26570000" },
                        new() { Id = 10, Name = "Krompachy", Latitude = "48.91447000", Longitude = "20.87514000" },
                        new() { Id = 11, Name = "Medzev", Latitude = "48.70041000", Longitude = "20.89367000" },
                        new() { Id = 12, Name = "Michalovce", Latitude = "48.75434000", Longitude = "21.91950000" },
                        new() { Id = 13, Name = "Moldava nad Bodvou", Latitude = "48.61428000", Longitude = "20.99957000" },
                        new() { Id = 14, Name = "Okres Gelnica", Latitude = "48.85207000", Longitude = "20.93385000" },
                        new() { Id = 15, Name = "Okres Kosice-okolie", Latitude = "48.77897000", Longitude = "21.41373000" },
                        new() { Id = 16, Name = "Okres Michalovce", Latitude = "48.75000000", Longitude = "21.93333000" },
                        new() { Id = 17, Name = "Okres Rožňava", Latitude = "48.66667000", Longitude = "20.53333000" },
                        new() { Id = 18, Name = "Okres Sobrance", Latitude = "48.74247000", Longitude = "22.18197000" },
                        new() { Id = 19, Name = "Okres Spišská Nová Ves", Latitude = "48.95000000", Longitude = "20.56667000" },
                        new() { Id = 20, Name = "Okres Trebišov", Latitude = "48.63333000", Longitude = "21.71667000" },
                        new() { Id = 21, Name = "Rožňava", Latitude = "48.66009000", Longitude = "20.53758000" },
                        new() { Id = 22, Name = "Sečovce", Latitude = "48.70074000", Longitude = "21.66104000" },
                        new() { Id = 23, Name = "Sobrance", Latitude = "48.74455000", Longitude = "22.18136000" },
                        new() { Id = 24, Name = "Spišská Nová Ves", Latitude = "48.94464000", Longitude = "20.56153000" },
                        new() { Id = 25, Name = "Strážske", Latitude = "48.87350000", Longitude = "21.83668000" },
                        new() { Id = 26, Name = "Trebišov", Latitude = "48.62858000", Longitude = "21.71954000" },
                        new() { Id = 27, Name = "Vinné", Latitude = "48.80965000", Longitude = "21.96757000" },
                        new() { Id = 28, Name = "Žehra", Latitude = "48.97960000", Longitude = "20.79170000" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Nitra",
                    StateCode = "",
                    Latitude = "48.31295000",
                    Longitude = "18.08945930",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Hurbanovo", Latitude = "47.86984000", Longitude = "18.19233000" },
                        new() { Id = 2, Name = "Kolárovo", Latitude = "47.92294000", Longitude = "17.98467000" },
                        new() { Id = 3, Name = "Komárno", Latitude = "47.76356000", Longitude = "18.12263000" },
                        new() { Id = 4, Name = "Levice", Latitude = "48.21563000", Longitude = "18.60705000" },
                        new() { Id = 5, Name = "Nitra", Latitude = "48.30763000", Longitude = "18.08453000" },
                        new() { Id = 6, Name = "Nové Zámky", Latitude = "47.98544000", Longitude = "18.16195000" },
                        new() { Id = 7, Name = "Okres Komárno", Latitude = "47.76667000", Longitude = "18.13333000" },
                        new() { Id = 8, Name = "Okres Levice", Latitude = "48.21667000", Longitude = "18.60000000" },
                        new() { Id = 9, Name = "Okres Nitra", Latitude = "48.31667000", Longitude = "18.08333000" },
                        new() { Id = 10, Name = "Okres Nové Zámky", Latitude = "47.98333000", Longitude = "18.16667000" },
                        new() { Id = 11, Name = "Okres Šaľa", Latitude = "48.14770000", Longitude = "17.87306000" },
                        new() { Id = 12, Name = "Okres Topoľčany", Latitude = "48.56667000", Longitude = "18.18333000" },
                        new() { Id = 13, Name = "Okres Zlaté Moravce", Latitude = "48.38294000", Longitude = "18.39842000" },
                        new() { Id = 14, Name = "Šahy", Latitude = "48.07408000", Longitude = "18.94946000" },
                        new() { Id = 15, Name = "Šaľa", Latitude = "48.15127000", Longitude = "17.88062000" },
                        new() { Id = 16, Name = "Štúrovo", Latitude = "47.79495000", Longitude = "18.71750000" },
                        new() { Id = 17, Name = "Šurany", Latitude = "48.08613000", Longitude = "18.18447000" },
                        new() { Id = 18, Name = "Svodín", Latitude = "47.91054000", Longitude = "18.49967000" },
                        new() { Id = 19, Name = "Tlmače", Latitude = "48.28926000", Longitude = "18.53152000" },
                        new() { Id = 20, Name = "Topoľčany", Latitude = "48.56361000", Longitude = "18.16712000" },
                        new() { Id = 21, Name = "Vráble", Latitude = "48.24371000", Longitude = "18.30846000" },
                        new() { Id = 22, Name = "Želiezovce", Latitude = "48.05075000", Longitude = "18.65421000" },
                        new() { Id = 23, Name = "Zlaté Moravce", Latitude = "48.38553000", Longitude = "18.40063000" }
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Prešov",
                    StateCode = "",
                    Latitude = "49.11176850",
                    Longitude = "21.18759780",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bardejov", Latitude = "49.29175000", Longitude = "21.27271000" },
                        new() { Id = 2, Name = "Chlmec", Latitude = "48.88628000", Longitude = "21.93930000" },
                        new() { Id = 3, Name = "Giraltovce", Latitude = "49.11398000", Longitude = "21.51731000" },
                        new() { Id = 4, Name = "Humenné", Latitude = "48.93707000", Longitude = "21.91625000" },
                        new() { Id = 5, Name = "Kežmarok", Latitude = "49.13571000", Longitude = "20.43352000" },
                        new() { Id = 6, Name = "Levoča", Latitude = "49.02173000", Longitude = "20.59212000" },
                        new() { Id = 7, Name = "Lipany", Latitude = "49.15376000", Longitude = "20.96382000" },
                        new() { Id = 8, Name = "Ľubica", Latitude = "49.11667000", Longitude = "20.45000000" },
                        new() { Id = 9, Name = "Medzilaborce", Latitude = "49.27195000", Longitude = "21.90073000" },
                        new() { Id = 10, Name = "Nová Lesná", Latitude = "49.12253000", Longitude = "20.26737000" },
                        new() { Id = 11, Name = "Okres Bardejov", Latitude = "49.28333000", Longitude = "21.28333000" },
                        new() { Id = 12, Name = "Okres Humenné", Latitude = "48.93333000", Longitude = "21.91667000" },
                        new() { Id = 13, Name = "Okres Kežmarok", Latitude = "49.13593000", Longitude = "20.42929000" },
                        new() { Id = 14, Name = "Okres Levoča", Latitude = "49.01986000", Longitude = "20.57688000" },
                        new() { Id = 15, Name = "Okres Medzilaborce", Latitude = "49.27062000", Longitude = "21.90200000" },
                        new() { Id = 16, Name = "Okres Poprad", Latitude = "49.05000000", Longitude = "20.30000000" },
                        new() { Id = 17, Name = "Okres Prešov", Latitude = "49.00000000", Longitude = "21.25000000" },
                        new() { Id = 18, Name = "Okres Sabinov", Latitude = "49.10115000", Longitude = "21.09844000" },
                        new() { Id = 19, Name = "Okres Snina", Latitude = "48.98579000", Longitude = "22.15059000" },
                        new() { Id = 20, Name = "Okres Stará Ĺubovňa", Latitude = "49.30000000", Longitude = "20.70000000" },
                        new() { Id = 21, Name = "Okres Stropkov", Latitude = "49.20249000", Longitude = "21.65025000" },
                        new() { Id = 22, Name = "Okres Svidník", Latitude = "49.30000000", Longitude = "21.56667000" },
                        new() { Id = 23, Name = "Okres Vranov nad Topľou", Latitude = "48.90000000", Longitude = "21.68333000" },
                        new() { Id = 24, Name = "Podolínec", Latitude = "49.25869000", Longitude = "20.53600000" },
                        new() { Id = 25, Name = "Poprad", Latitude = "49.06144000", Longitude = "20.29798000" },
                        new() { Id = 26, Name = "Prešov", Latitude = "48.99839000", Longitude = "21.23393000" },
                        new() { Id = 27, Name = "Sabinov", Latitude = "49.10309000", Longitude = "21.09880000" },
                        new() { Id = 28, Name = "Snina", Latitude = "48.98857000", Longitude = "22.15099000" },
                        new() { Id = 29, Name = "Spišská Belá", Latitude = "49.18725000", Longitude = "20.45948000" },
                        new() { Id = 30, Name = "Spišské Podhradie", Latitude = "49.00088000", Longitude = "20.75307000" },
                        new() { Id = 31, Name = "Stará Ľubovňa", Latitude = "49.29859000", Longitude = "20.68620000" },
                        new() { Id = 32, Name = "Štrba", Latitude = "49.05913000", Longitude = "20.07975000" },
                        new() { Id = 33, Name = "Stropkov", Latitude = "49.20211000", Longitude = "21.65216000" },
                        new() { Id = 34, Name = "Svidník", Latitude = "49.30819000", Longitude = "21.57030000" },
                        new() { Id = 35, Name = "Svit", Latitude = "49.06014000", Longitude = "20.20695000" },
                        new() { Id = 36, Name = "Vranov nad Topľou", Latitude = "48.88836000", Longitude = "21.68479000" },
                        new() { Id = 37, Name = "Vrbov", Latitude = "49.08764000", Longitude = "20.42530000" },
                        new() { Id = 38, Name = "Vyšné Ružbachy", Latitude = "49.30387000", Longitude = "20.56558000" },
                        new() { Id = 39, Name = "Vysoké Tatry", Latitude = "49.13637000", Longitude = "20.24386000" },
                        new() { Id = 40, Name = "Ždiar", Latitude = "49.27100000", Longitude = "20.26239000" }
                    }
                },

                new()
                {
                    Id = 6,
                    Name = "Trenčín",
                    StateCode = "",
                    Latitude = "48.91380300",
                    Longitude = "18.09311970",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bánovce nad Bebravou", Latitude = "48.72130000", Longitude = "18.25754000" },
                        new() { Id = 2, Name = "Bojnice", Latitude = "48.78511000", Longitude = "18.58640000" },
                        new() { Id = 3, Name = "Brezová pod Bradlom", Latitude = "48.66349000", Longitude = "17.53905000" },
                        new() { Id = 4, Name = "Čachtice", Latitude = "48.71226000", Longitude = "17.78704000" },
                        new() { Id = 5, Name = "Dubnica nad Váhom", Latitude = "48.95981000", Longitude = "18.16634000" },
                        new() { Id = 6, Name = "Handlová", Latitude = "48.72760000", Longitude = "18.76012000" },
                        new() { Id = 7, Name = "Ilava", Latitude = "48.99769000", Longitude = "18.23530000" },
                        new() { Id = 8, Name = "Lehota pod Vtáčnikom", Latitude = "48.69138000", Longitude = "18.59944000" },
                        new() { Id = 9, Name = "Myjava", Latitude = "48.75876000", Longitude = "17.56866000" },
                        new() { Id = 10, Name = "Nemšová", Latitude = "48.96702000", Longitude = "18.11892000" },
                        new() { Id = 11, Name = "Nová Dubnica", Latitude = "48.93479000", Longitude = "18.14632000" },
                        new() { Id = 12, Name = "Nováky", Latitude = "48.71106000", Longitude = "18.53389000" },
                        new() { Id = 13, Name = "Nové Mesto nad Váhom", Latitude = "48.75763000", Longitude = "17.83090000" },
                        new() { Id = 14, Name = "Okres Bánovce nad Bebravou", Latitude = "48.71908000", Longitude = "18.25773000" },
                        new() { Id = 15, Name = "Okres Ilava", Latitude = "48.99641000", Longitude = "18.23374000" },
                        new() { Id = 16, Name = "Okres Myjava", Latitude = "48.75000000", Longitude = "17.58333000" },
                        new() { Id = 17, Name = "Okres Nové Mesto nad Váhom", Latitude = "48.75466000", Longitude = "17.83506000" },
                        new() { Id = 18, Name = "Okres Partizánske", Latitude = "48.62613000", Longitude = "18.37957000" },
                        new() { Id = 19, Name = "Okres Považská Bystrica", Latitude = "49.11667000", Longitude = "18.45000000" },
                        new() { Id = 20, Name = "Okres Prievidza", Latitude = "48.76667000", Longitude = "18.63333000" },
                        new() { Id = 21, Name = "Okres Púchov", Latitude = "49.12406000", Longitude = "18.32477000" },
                        new() { Id = 22, Name = "Okres Trenčín", Latitude = "48.89520000", Longitude = "18.04264000" },
                        new() { Id = 23, Name = "Partizánske", Latitude = "48.62861000", Longitude = "18.38455000" },
                        new() { Id = 24, Name = "Považská Bystrica", Latitude = "49.12153000", Longitude = "18.42169000" },
                        new() { Id = 25, Name = "Prievidza", Latitude = "48.77446000", Longitude = "18.62750000" },
                        new() { Id = 26, Name = "Púchov", Latitude = "49.12494000", Longitude = "18.32597000" },
                        new() { Id = 27, Name = "Stará Turá", Latitude = "48.77721000", Longitude = "17.69433000" },
                        new() { Id = 28, Name = "Trenčianske Teplice", Latitude = "48.91063000", Longitude = "18.16691000" },
                        new() { Id = 29, Name = "Trenčín", Latitude = "48.89452000", Longitude = "18.04436000" }
                    }
                },

                new()
                {
                    Id = 7,
                    Name = "Trnava",
                    StateCode = "",
                    Latitude = "48.37676520",
                    Longitude = "17.58581750",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Dunajská Streda", Latitude = "47.99268000", Longitude = "17.61211000" },
                        new() { Id = 2, Name = "Gabčíkovo", Latitude = "47.89211000", Longitude = "17.57884000" },
                        new() { Id = 3, Name = "Galanta", Latitude = "48.19001000", Longitude = "17.72747000" },
                        new() { Id = 4, Name = "Gbely", Latitude = "48.71800000", Longitude = "17.11628000" },
                        new() { Id = 5, Name = "Hlohovec", Latitude = "48.43174000", Longitude = "17.80310000" },
                        new() { Id = 6, Name = "Holíč", Latitude = "48.81105000", Longitude = "17.16238000" },
                        new() { Id = 7, Name = "Leopoldov", Latitude = "48.44575000", Longitude = "17.76458000" },
                        new() { Id = 8, Name = "Okres Dunajská Streda", Latitude = "47.99635000", Longitude = "17.60937000" },
                        new() { Id = 9, Name = "Okres Galanta", Latitude = "48.20000000", Longitude = "17.71667000" },
                        new() { Id = 10, Name = "Okres Hlohovec", Latitude = "48.41667000", Longitude = "17.75000000" },
                        new() { Id = 11, Name = "Okres Piešťany", Latitude = "48.59064000", Longitude = "17.82679000" },
                        new() { Id = 12, Name = "Okres Senica", Latitude = "48.68333000", Longitude = "17.36667000" },
                        new() { Id = 13, Name = "Okres Skalica", Latitude = "48.75000000", Longitude = "17.16667000" },
                        new() { Id = 14, Name = "Okres Trnava", Latitude = "48.36667000", Longitude = "17.60000000" },
                        new() { Id = 15, Name = "Piešťany", Latitude = "48.59479000", Longitude = "17.82591000" },
                        new() { Id = 16, Name = "Šamorín", Latitude = "48.03015000", Longitude = "17.30972000" },
                        new() { Id = 17, Name = "Senica", Latitude = "48.67922000", Longitude = "17.36697000" },
                        new() { Id = 18, Name = "Skalica", Latitude = "48.84490000", Longitude = "17.22635000" },
                        new() { Id = 19, Name = "Sládkovičovo", Latitude = "48.20137000", Longitude = "17.63852000" },
                        new() { Id = 20, Name = "Smolenice", Latitude = "48.50478000", Longitude = "17.43067000" },
                        new() { Id = 21, Name = "Trnava", Latitude = "48.37741000", Longitude = "17.58723000" },
                        new() { Id = 22, Name = "Veľký Meder", Latitude = "47.85798000", Longitude = "17.76884000" },
                        new() { Id = 23, Name = "Vrbové", Latitude = "48.61973000", Longitude = "17.72260000" }
                    }
                },

                new()
                {
                    Id = 8,
                    Name = "Žilina",
                    StateCode = "",
                    Latitude = "49.17754550",
                    Longitude = "19.20581800",
                    Type = "region",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Bytča", Latitude = "49.22404000", Longitude = "18.55878000" },
                        new() { Id = 2, Name = "Čadca", Latitude = "49.43503000", Longitude = "18.78895000" },
                        new() { Id = 3, Name = "Dolný Kubín", Latitude = "49.20983000", Longitude = "19.30341000" },
                        new() { Id = 4, Name = "Hybe", Latitude = "49.04439000", Longitude = "19.82895000" },
                        new() { Id = 5, Name = "Krasňany", Latitude = "49.21491000", Longitude = "18.88718000" },
                        new() { Id = 6, Name = "Kysucké Nové Mesto", Latitude = "49.30000000", Longitude = "18.78333000" },
                        new() { Id = 7, Name = "Liptovský Hrádok", Latitude = "49.03962000", Longitude = "19.72335000" },
                        new() { Id = 8, Name = "Liptovský Mikuláš", Latitude = "49.08061000", Longitude = "19.62218000" },
                        new() { Id = 9, Name = "Lúčky", Latitude = "49.12944000", Longitude = "19.40228000" },
                        new() { Id = 10, Name = "Martin", Latitude = "49.06651000", Longitude = "18.92399000" },
                        new() { Id = 11, Name = "Námestovo", Latitude = "49.40790000", Longitude = "19.48032000" },
                        new() { Id = 12, Name = "Nižná", Latitude = "49.31046000", Longitude = "19.52428000" },
                        new() { Id = 13, Name = "Okres Bytča", Latitude = "49.22267000", Longitude = "18.55844000" },
                        new() { Id = 14, Name = "Okres Čadca", Latitude = "49.43333000", Longitude = "18.78333000" },
                        new() { Id = 15, Name = "Okres Dolný Kubín", Latitude = "49.20000000", Longitude = "19.30000000" },
                        new() { Id = 16, Name = "Okres Kysucké Nové Mesto", Latitude = "49.30206000", Longitude = "18.78603000" },
                        new() { Id = 17, Name = "Okres Liptovský Mikuláš", Latitude = "49.08333000", Longitude = "19.61667000" },
                        new() { Id = 18, Name = "Okres Martin", Latitude = "49.06667000", Longitude = "18.93333000" },
                        new() { Id = 19, Name = "Okres Namestovo", Latitude = "49.40651000", Longitude = "19.47670000" },
                        new() { Id = 20, Name = "Okres Ružomberok", Latitude = "49.07494000", Longitude = "19.30083000" },
                        new() { Id = 21, Name = "Okres Turčianske Teplice", Latitude = "48.86283000", Longitude = "18.85759000" },
                        new() { Id = 22, Name = "Okres Tvrdošín", Latitude = "49.33421000", Longitude = "19.55461000" },
                        new() { Id = 23, Name = "Okres Žilina", Latitude = "49.22303000", Longitude = "18.74044000" },
                        new() { Id = 24, Name = "Oravská Lesná", Latitude = "49.36672000", Longitude = "19.18093000" },
                        new() { Id = 25, Name = "Oravský Podzámok", Latitude = "49.25939000", Longitude = "19.35690000" },
                        new() { Id = 26, Name = "Pribylina", Latitude = "49.09950000", Longitude = "19.79427000" },
                        new() { Id = 27, Name = "Rajec", Latitude = "49.08899000", Longitude = "18.64007000" },
                        new() { Id = 28, Name = "Ružomberok", Latitude = "49.07480000", Longitude = "19.30751000" },
                        new() { Id = 29, Name = "Terchová", Latitude = "49.25895000", Longitude = "19.02935000" },
                        new() { Id = 30, Name = "Trstená", Latitude = "49.36101000", Longitude = "19.61249000" },
                        new() { Id = 31, Name = "Turčianske Teplice", Latitude = "48.86225000", Longitude = "18.86048000" },
                        new() { Id = 32, Name = "Turzovka", Latitude = "49.40429000", Longitude = "18.62258000" },
                        new() { Id = 33, Name = "Tvrdošín", Latitude = "49.33700000", Longitude = "19.55600000" },
                        new() { Id = 34, Name = "Vrútky", Latitude = "49.11328000", Longitude = "18.91714000" },
                        new() { Id = 35, Name = "Žilina", Latitude = "49.22315000", Longitude = "18.73941000" }
                    }
                }
            }
        };
    }
}
