// ⚠️ WARNING: This file is automatically generated by scripts/generate-world.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify the source data in countries-states-cities-database and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Countries
{
    public static class Taiwan
    {
        public static Country Data { get; } = new()
        {
            Id = 216,
            Name = "Taiwan",
            Iso3 = "TWN",
            Iso2 = "TW",
            NumericCode = "158",
            PhoneCode = "886",
            Capital = "Taipei",
            Currency = "TWD",
            CurrencyName = "New Taiwan dollar",
            CurrencySymbol = "$",
            Tld = ".tw",
            Native = "臺灣",
            Region = "Asia",
            RegionId = 3,
            Subregion = "Eastern Asia",
            SubregionId = 12,
            Nationality = "Chinese, Taiwanese",
            Latitude = "23.50000000",
            Longitude = "121.00000000",
            Emoji = "🇹🇼",
            EmojiU = "U+1F1F9 U+1F1FC",
            Timezones = new()
            {
                new() { ZoneName = "Asia/Taipei", GmtOffset = 28800, GmtOffsetName = "UTC+08:00", Abbreviation = "CST", TzName = "China Standard Time" }
            },
            Translations = new()
            {
                ["br"] = "Taiwan",
                ["ko"] = "대만",
                ["pt-BR"] = "Taiwan",
                ["pt"] = "Taiwan",
                ["nl"] = "Taiwan",
                ["hr"] = "Tajvan",
                ["fa"] = "تایوان",
                ["de"] = "Taiwan",
                ["es"] = "Taiwán",
                ["fr"] = "Taïwan",
                ["ja"] = "台湾（中華民国）",
                ["it"] = "Taiwan",
                ["zh-CN"] = "中国台湾",
                ["tr"] = "Tayvan",
                ["ru"] = "Тайвань",
                ["uk"] = "Тайвань",
                ["pl"] = "Tajwan",
                ["hi"] = "ताइवान",
                ["ar"] = "تايوان"
            },
            States = new()
            {

                new()
                {
                    Id = 1,
                    Name = "Changhua",
                    StateCode = "",
                    Latitude = "24.07556670",
                    Longitude = "120.54446670",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Changhua", Latitude = "23.95361000", Longitude = "120.49083000" },
                        new() { Id = 2, Name = "Yuanlin", Latitude = "23.95671000", Longitude = "120.57608000" }
                    }
                },

                new()
                {
                    Id = 2,
                    Name = "Chiayi",
                    StateCode = "",
                    Latitude = "23.45916640",
                    Longitude = "120.29300040",
                    Type = "city",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Chiayi", Latitude = "23.47722000", Longitude = "120.44527000" },
                        new() { Id = 2, Name = "Pizitou", Latitude = "23.48556000", Longitude = "120.44472000" }
                    }
                },

                new()
                {
                    Id = 3,
                    Name = "Chiayi County",
                    StateCode = "",
                    Latitude = "23.49620556",
                    Longitude = "120.64187500",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Budai", Latitude = "23.36000000", Longitude = "120.17000000" },
                        new() { Id = 2, Name = "Chiayi", Latitude = "23.46333000", Longitude = "120.58166000" },
                        new() { Id = 3, Name = "Dalin", Latitude = "23.59888889", Longitude = "120.47000000" },
                        new() { Id = 4, Name = "Minxiong", Latitude = "23.55039900", Longitude = "120.44569600" }
                    }
                },

                new()
                {
                    Id = 4,
                    Name = "Hsinchu",
                    StateCode = "",
                    Latitude = "24.81382870",
                    Longitude = "120.96747980",
                    Type = "city",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Hsinchu", Latitude = "24.67416000", Longitude = "121.16111000" }
                    }
                },

                new()
                {
                    Id = 5,
                    Name = "Hsinchu County",
                    StateCode = "",
                    Latitude = "24.83333333",
                    Longitude = "121.01472222",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Hsinchu", Latitude = "24.80361000", Longitude = "120.96861000" },
                        new() { Id = 2, Name = "Hukou", Latitude = "24.90000000", Longitude = "121.05000000" },
                        new() { Id = 3, Name = "Zhubei", Latitude = "24.83333333", Longitude = "121.01194444" }
                    }
                },

                new()
                {
                    Id = 6,
                    Name = "Hualien",
                    StateCode = "",
                    Latitude = "23.98715890",
                    Longitude = "121.60157140",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Hualien", Latitude = "23.78166000", Longitude = "121.39333000" }
                    }
                },

                new()
                {
                    Id = 7,
                    Name = "Kaohsiung",
                    StateCode = "",
                    Latitude = "22.62033480",
                    Longitude = "120.31203750",
                    Type = "special municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Kaohsiung", Latitude = "22.61626000", Longitude = "120.31333000" }
                    }
                },

                new()
                {
                    Id = 8,
                    Name = "Keelung",
                    StateCode = "",
                    Latitude = "25.13172320",
                    Longitude = "121.74465200",
                    Type = "city",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 9,
                    Name = "Kinmen",
                    StateCode = "",
                    Latitude = "24.43676380",
                    Longitude = "118.31864350",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Jincheng", Latitude = "24.43415000", Longitude = "118.31712000" },
                        new() { Id = 2, Name = "Kinmen", Latitude = "24.45333000", Longitude = "118.38861000" }
                    }
                },

                new()
                {
                    Id = 10,
                    Name = "Lienchiang",
                    StateCode = "",
                    Latitude = "26.15779510",
                    Longitude = "119.95197560",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Lienchiang", Latitude = "26.37004000", Longitude = "120.49545000" },
                        new() { Id = 2, Name = "Nangan", Latitude = "26.15039000", Longitude = "119.93284000" }
                    }
                },

                new()
                {
                    Id = 11,
                    Name = "Miaoli",
                    StateCode = "",
                    Latitude = "24.56015900",
                    Longitude = "120.82142650",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Miaoli", Latitude = "24.48972000", Longitude = "120.90638000" }
                    }
                },

                new()
                {
                    Id = 12,
                    Name = "Nantou",
                    StateCode = "",
                    Latitude = "23.90235000",
                    Longitude = "120.69091670",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Lugu", Latitude = "23.74639000", Longitude = "120.75250000" },
                        new() { Id = 2, Name = "Nantou", Latitude = "23.83419000", Longitude = "120.92704000" },
                        new() { Id = 3, Name = "Puli", Latitude = "23.96639000", Longitude = "120.96952000" },
                        new() { Id = 4, Name = "Zhongxing New Village", Latitude = "23.95908000", Longitude = "120.68516000" }
                    }
                },

                new()
                {
                    Id = 13,
                    Name = "New Taipei",
                    StateCode = "",
                    Latitude = "25.01199700",
                    Longitude = "121.46566190",
                    Type = "special municipality",
                    Cities = new()
                    {
                    }
                },

                new()
                {
                    Id = 14,
                    Name = "Penghu",
                    StateCode = "",
                    Latitude = "23.56969400",
                    Longitude = "119.56645430",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Magong", Latitude = "23.56540000", Longitude = "119.58627000" },
                        new() { Id = 2, Name = "Penghu", Latitude = "23.57111000", Longitude = "119.61138000" }
                    }
                },

                new()
                {
                    Id = 15,
                    Name = "Pingtung",
                    StateCode = "",
                    Latitude = "22.66284680",
                    Longitude = "120.49156770",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Donggang", Latitude = "22.46515000", Longitude = "120.44927000" },
                        new() { Id = 2, Name = "Hengchun", Latitude = "22.00417000", Longitude = "120.74389000" },
                        new() { Id = 3, Name = "Pingtung", Latitude = "22.49555000", Longitude = "120.61444000" }
                    }
                },

                new()
                {
                    Id = 16,
                    Name = "Taichung",
                    StateCode = "",
                    Latitude = "24.16316200",
                    Longitude = "120.64782820",
                    Type = "special municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Taichung", Latitude = "24.14690000", Longitude = "120.68390000" }
                    }
                },

                new()
                {
                    Id = 17,
                    Name = "Tainan",
                    StateCode = "",
                    Latitude = "22.99123480",
                    Longitude = "120.18498200",
                    Type = "special municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Tainan", Latitude = "22.99083000", Longitude = "120.21333000" },
                        new() { Id = 2, Name = "Yujing", Latitude = "23.12493000", Longitude = "120.46138000" }
                    }
                },

                new()
                {
                    Id = 18,
                    Name = "Taipei",
                    StateCode = "",
                    Latitude = "25.03296940",
                    Longitude = "121.56541770",
                    Type = "special municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Banqiao", Latitude = "25.01427000", Longitude = "121.46719000" },
                        new() { Id = 2, Name = "Jiufen", Latitude = "25.10957000", Longitude = "121.84424000" },
                        new() { Id = 3, Name = "Taipei", Latitude = "25.04776000", Longitude = "121.53185000" }
                    }
                },

                new()
                {
                    Id = 19,
                    Name = "Taitung",
                    StateCode = "",
                    Latitude = "22.75604470",
                    Longitude = "121.14565380",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Taitung", Latitude = "22.88361000", Longitude = "121.04833000" }
                    }
                },

                new()
                {
                    Id = 20,
                    Name = "Taoyuan",
                    StateCode = "",
                    Latitude = "24.99362810",
                    Longitude = "121.30097980",
                    Type = "special municipality",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Daxi", Latitude = "24.88373000", Longitude = "121.29043000" },
                        new() { Id = 2, Name = "Taoyuan", Latitude = "24.89500000", Longitude = "121.24611000" }
                    }
                },

                new()
                {
                    Id = 21,
                    Name = "Yilan",
                    StateCode = "",
                    Latitude = "24.73027910",
                    Longitude = "121.76311490",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Yilan", Latitude = "24.54250000", Longitude = "121.63361000" }
                    }
                },

                new()
                {
                    Id = 22,
                    Name = "Yunlin",
                    StateCode = "",
                    Latitude = "23.69907750",
                    Longitude = "120.52455110",
                    Type = "county",
                    Cities = new()
                    {
                        new() { Id = 1, Name = "Douliu", Latitude = "23.70944000", Longitude = "120.54333000" },
                        new() { Id = 2, Name = "Yunlin", Latitude = "23.70701000", Longitude = "120.38481000" }
                    }
                }
            }
        };
    }
}
