// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class AlbanyGa
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "albany-ga",
            Name = "Albany, GA",
            ShortName = "Albany",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 145451,
            CsaId = null,
            Latitude = "31.57851000",
            Longitude = "-84.15574000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 12, StateName = "Georgia", CityId = 6, Name = "Albany" }
            }
        };
    }
}
