// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class AmarilloTx
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "amarillo-tx",
            Name = "Amarillo, TX",
            ShortName = "Amarillo",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 274650,
            CsaId = "csa-amarillo-borger-tx",
            Latitude = "35.22200000",
            Longitude = "-101.83130000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 48, StateName = "Texas", CityId = 21, Name = "Amarillo" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 48, StateName = "Texas", CityId = 171, Name = "Canyon" }
            }
        };
    }
}
