// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class BeaumontPortArthurTx
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "beaumont-port-arthur-tx",
            Name = "Beaumont–Port Arthur, TX",
            ShortName = "Beaumont",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 398733,
            CsaId = null,
            Latitude = "30.08605000",
            Longitude = "-94.10185000",
            TimeZoneId = "America/Chicago",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 48, StateName = "Texas", CityId = 76, Name = "Beaumont" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 48, StateName = "Texas", CityId = 911, Name = "Port Arthur" }
            }
        };
    }
}
