// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class BellinghamWa
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "bellingham-wa",
            Name = "Bellingham, WA",
            ShortName = "Bellingham",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 234954,
            CsaId = null,
            Latitude = "48.75955000",
            Longitude = "-122.48822000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 54, StateName = "Washington", CityId = 26, Name = "Bellingham" }
            }
        };
    }
}
