// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class BismarckNd
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "bismarck-nd",
            Name = "Bismarck, ND",
            ShortName = "Bismarck",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 139183,
            CsaId = null,
            Latitude = "46.80833000",
            Longitude = "-100.78374000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 37, StateName = "North Dakota", CityId = 11, Name = "Bismarck" }
            }
        };
    }
}
