// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class BurlingtonNc
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "burlington-nc",
            Name = "Burlington, NC",
            ShortName = "Burlington",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 183040,
            CsaId = "csa-greensboro-winston-salem-high-point-nc",
            Latitude = "36.09569000",
            Longitude = "-79.43780000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 36, StateName = "North Carolina", CityId = 64, Name = "Burlington" }
            }
        };
    }
}
