// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class CantonMassillonOh
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "canton-massillon-oh",
            Name = "Canton–Massillon, OH",
            ShortName = "Canton",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 400551,
            CsaId = "csa-cleveland-akron-canton-oh",
            Latitude = "40.79895000",
            Longitude = "-81.37845000",
            TimeZoneId = "America/New_York",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 39, StateName = "Ohio", CityId = 101, Name = "Canton" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 39, StateName = "Ohio", CityId = 399, Name = "Massillon" }
            }
        };
    }
}
