// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class CasperWy
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "casper-wy",
            Name = "Casper, WY",
            ShortName = "Casper",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 80410,
            CsaId = null,
            Latitude = "42.86663000",
            Longitude = "-106.31308000",
            TimeZoneId = "America/Denver",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 57, StateName = "Wyoming", CityId = 11, Name = "Casper" }
            }
        };
    }
}
