// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class CedarRapidsIa
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "cedar-rapids-ia",
            Name = "Cedar Rapids, IA",
            ShortName = "Cedar Rapids",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 278677,
            CsaId = "csa-cedar-rapids-iowa-city-ia",
            Latitude = "42.00833000",
            Longitude = "-91.64407000",
            TimeZoneId = "America/Chicago",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 18, StateName = "Iowa", CityId = 57, Name = "Cedar Rapids" }
            }
        };
    }
}
