// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class ChampaignUrbanaIl
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "champaign-urbana-il",
            Name = "Champaign–Urbana, IL",
            ShortName = "Champaign",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 242453,
            CsaId = "csa-champaign-urbana-danville-il",
            Latitude = "40.11642000",
            Longitude = "-88.24338000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 16, StateName = "Illinois", CityId = 117, Name = "Champaign" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 16, StateName = "Illinois", CityId = 772, Name = "Urbana" }
            }
        };
    }
}
