// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class ChBasel
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "ch-basel",
            Name = "Basel trinational",
            ShortName = "Basel",
            CountryIso2 = "CH",
            Countries = new() { "CH", "FR", "DE" },
            Code = null,
            Type = MetroAreaType.Other,
            Population = null,
            CsaId = null,
            Latitude = "47.55960000",
            Longitude = "7.58800000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "CH", StateId = null, StateName = "Basel-Stadt", CityId = null, Name = "Basel" },
                new() { Type = MetroMemberType.City, CountryIso2 = "FR", StateId = null, StateName = "Haut-Rhin", CityId = null, Name = "Saint-Louis" },
                new() { Type = MetroMemberType.City, CountryIso2 = "DE", StateId = null, StateName = "Baden-Württemberg", CityId = null, Name = "Weil am Rhein" }
            }
        };
    }
}
