// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class CoeurDAleneId
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "coeur-d-alene-id",
            Name = "Coeur d'Alene, ID",
            ShortName = "Coeur d'Alene",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 188323,
            CsaId = "csa-spokane-spokane-valley-coeur-d-alene-wa-id",
            Latitude = "47.67768000",
            Longitude = "-116.78047000",
            TimeZoneId = "America/Los_Angeles",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 15, StateName = "Idaho", CityId = 34, Name = "Coeur d'Alene" }
            }
        };
    }
}
