// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class DavenportMolineRockIslandIaIl
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "davenport-moline-rock-island-ia-il",
            Name = "Davenport–Moline–Rock Island, IA-IL",
            ShortName = "Davenport",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 381801,
            CsaId = "csa-davenport-moline-ia-il",
            Latitude = "41.52364000",
            Longitude = "-90.57764000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 18, StateName = "Iowa", CityId = 91, Name = "Davenport" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 16, StateName = "Illinois", CityId = 505, Name = "Moline" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 16, StateName = "Illinois", CityId = 657, Name = "Rock Island" }
            }
        };
    }
}
