// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class DothanAl
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "dothan-al",
            Name = "Dothan, AL",
            ShortName = "Dothan",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 154766,
            CsaId = "csa-dothan-enterprise-ozark-al",
            Latitude = "31.22323000",
            Longitude = "-85.39049000",
            TimeZoneId = "America/Chicago",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 1, StateName = "Alabama", CityId = 108, Name = "Dothan" }
            }
        };
    }
}
