// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class ElCentroCa
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "el-centro-ca",
            Name = "El Centro, CA",
            ShortName = "El Centro",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 181724,
            CsaId = null,
            Latitude = "32.79200000",
            Longitude = "-115.56305000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 6, StateName = "California", CityId = 299, Name = "El Centro" }
            }
        };
    }
}
