// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class FarmingtonNm
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "farmington-nm",
            Name = "Farmington, NM",
            ShortName = "Farmington",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 120817,
            CsaId = null,
            Latitude = "36.72806000",
            Longitude = "-108.21869000",
            TimeZoneId = "America/Denver",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 34, StateName = "New Mexico", CityId = 58, Name = "Farmington" }
            }
        };
    }
}
