// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class HanfordCorcoranCa
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "hanford-corcoran-ca",
            Name = "Hanford–Corcoran, CA",
            ShortName = "Hanford",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 154913,
            CsaId = "csa-fresno-hanford-corcoran-ca",
            Latitude = "36.32745000",
            Longitude = "-119.64568000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 6, StateName = "California", CityId = 398, Name = "Hanford" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 6, StateName = "California", CityId = 219, Name = "Corcoran" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 6, StateName = "California", CityId = 528, Name = "Lemoore" }
            }
        };
    }
}
