// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class HickoryLenoirMorgantonNc
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "hickory-lenoir-morganton-nc",
            Name = "Hickory–Lenoir–Morganton, NC",
            ShortName = "Hickory",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 373031,
            CsaId = "csa-charlotte-concord-nc-sc",
            Latitude = "35.73319000",
            Longitude = "-81.34120000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 36, StateName = "North Carolina", CityId = 220, Name = "Hickory" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 36, StateName = "North Carolina", CityId = 269, Name = "Lenoir" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 36, StateName = "North Carolina", CityId = 322, Name = "Morganton" }
            }
        };
    }
}
