// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class InMumbai
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "in-mumbai",
            Name = "Mumbai Metropolitan Region",
            ShortName = "Mumbai",
            CountryIso2 = "IN",
            Countries = new() { "IN" },
            Code = null,
            Type = MetroAreaType.Other,
            Population = null,
            CsaId = null,
            Latitude = "19.07598000",
            Longitude = "72.87766000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "IN", StateId = 21, StateName = "Maharashtra", CityId = 327, Name = "Mumbai" },
                new() { Type = MetroMemberType.City, CountryIso2 = "IN", StateId = 21, StateName = "Maharashtra", CityId = 507, Name = "Thane" },
                new() { Type = MetroMemberType.City, CountryIso2 = "IN", StateId = 21, StateName = "Maharashtra", CityId = 357, Name = "Navi Mumbai" },
                new() { Type = MetroMemberType.City, CountryIso2 = "IN", StateId = 21, StateName = "Maharashtra", CityId = 214, Name = "Kalyan" }
            }
        };
    }
}
