// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class JacksonTn
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "jackson-tn",
            Name = "Jackson, TN",
            ShortName = "Jackson",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 183680,
            CsaId = null,
            Latitude = "35.61452000",
            Longitude = "-88.81395000",
            TimeZoneId = "America/Chicago",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 47, StateName = "Tennessee", CityId = 170, Name = "Jackson" }
            }
        };
    }
}
