// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class JacksonvilleNc
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "jacksonville-nc",
            Name = "Jacksonville, NC",
            ShortName = "Jacksonville",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 212954,
            CsaId = null,
            Latitude = "34.75405000",
            Longitude = "-77.43024000",
            TimeZoneId = "America/New_York",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 36, StateName = "North Carolina", CityId = 238, Name = "Jacksonville" }
            }
        };
    }
}
