// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class KankakeeIl
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "kankakee-il",
            Name = "Kankakee, IL",
            ShortName = "Kankakee",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 106410,
            CsaId = "csa-chicago-naperville-il-in-wi",
            Latitude = "41.12003000",
            Longitude = "-87.86115000",
            TimeZoneId = "America/Chicago",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 16, StateName = "Illinois", CityId = 376, Name = "Kankakee" }
            }
        };
    }
}
