// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class KeyWestFl
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "key-west-fl",
            Name = "Key West",
            ShortName = "Key West",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Micropolitan,
            Population = null,
            CsaId = null,
            Latitude = "24.55524000",
            Longitude = "-81.78163000",
            TimeZoneId = "America/New_York",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 11, StateName = "Florida", CityId = 364, Name = "Key West" }
            }
        };
    }
}
