// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class KiryasJoelPoughkeepsieNewburghNy
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "kiryas-joel-poughkeepsie-newburgh-ny",
            Name = "Kiryas Joel–Poughkeepsie–Newburgh, NY",
            ShortName = "Kiryas Joel",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 711730,
            CsaId = "csa-new-york-newark-ny-nj-ct-pa",
            Latitude = "41.34204000",
            Longitude = "-74.16792000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 474, Name = "Kiryas Joel" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 759, Name = "Poughkeepsie" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 635, Name = "Newburgh" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 715, Name = "Pawling" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = null, Name = "Bethel" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 295, Name = "Fishkill" }
            }
        };
    }
}
