// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class MyrtleBeachConwayNorthMyrtleBeachSc
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "myrtle-beach-conway-north-myrtle-beach-sc",
            Name = "Myrtle Beach–Conway–North Myrtle Beach, SC",
            ShortName = "Myrtle Beach",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 413391,
            CsaId = "csa-myrtle-beach-conway-sc",
            Latitude = "33.68906000",
            Longitude = "-78.88669000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 45, StateName = "South Carolina", CityId = 186, Name = "Myrtle Beach" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 45, StateName = "South Carolina", CityId = 63, Name = "Conway" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 45, StateName = "South Carolina", CityId = 195, Name = "North Myrtle Beach" }
            }
        };
    }
}
