// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class NaplesMarcoIslandFl
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "naples-marco-island-fl",
            Name = "Naples–Marco Island, FL",
            ShortName = "Naples",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 416233,
            CsaId = "csa-cape-coral-fort-myers-naples-fl",
            Latitude = "26.14234000",
            Longitude = "-81.79596000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 11, StateName = "Florida", CityId = 487, Name = "Naples" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 11, StateName = "Florida", CityId = 444, Name = "Marco Island" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 11, StateName = "Florida", CityId = 323, Name = "Immokalee" }
            }
        };
    }
}
