// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class NewHavenCt
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "new-haven-ct",
            Name = "New Haven, CT",
            ShortName = "New Haven",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 576718,
            CsaId = "csa-new-haven-hartford-waterbury-ct",
            Latitude = "41.30815000",
            Longitude = "-72.92816000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 8, StateName = "Connecticut", CityId = 90, Name = "New Haven" }
            }
        };
    }
}
