// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class PanamaCityPanamaCityBeachFl
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "panama-city-panama-city-beach-fl",
            Name = "Panama City–Panama City Beach, FL",
            ShortName = "Panama City",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 226221,
            CsaId = null,
            Latitude = "30.15946000",
            Longitude = "-85.65983000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 11, StateName = "Florida", CityId = 569, Name = "Panama City" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 11, StateName = "Florida", CityId = 570, Name = "Panama City Beach" }
            }
        };
    }
}
