// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class PikevilleKy
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "pikeville-ky",
            Name = "Pikeville",
            ShortName = "Pikeville",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Micropolitan,
            Population = null,
            CsaId = null,
            Latitude = "37.47927000",
            Longitude = "-82.51876000",
            TimeZoneId = "America/New_York",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 20, StateName = "Kentucky", CityId = 298, Name = "Pikeville" }
            }
        };
    }
}
