// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class PortlandVancouverHillsboroOrWa
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "portland-vancouver-hillsboro-or-wa",
            Name = "Portland–Vancouver–Hillsboro, OR-WA",
            ShortName = "Portland",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 2537904,
            CsaId = "csa-portland-vancouver-salem-or-wa",
            Latitude = "45.52345000",
            Longitude = "-122.67621000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 41, StateName = "Oregon", CityId = 179, Name = "Portland" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 54, StateName = "Washington", CityId = 389, Name = "Vancouver" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 41, StateName = "Oregon", CityId = 98, Name = "Hillsboro" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 54, StateName = "Washington", CityId = 318, Name = "Ridgefield" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 41, StateName = "Oregon", CityId = 224, Name = "Troutdale" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = null, StateName = null, CityId = null, Name = "Vancouver" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 41, StateName = "Oregon", CityId = 74, Name = "Forest Grove" }
            }
        };
    }
}
