// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class ReddingCa
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "redding-ca",
            Name = "Redding, CA",
            ShortName = "Redding",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 181121,
            CsaId = "csa-redding-red-bluff-ca",
            Latitude = "40.58654000",
            Longitude = "-122.39168000",
            TimeZoneId = "America/Los_Angeles",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 6, StateName = "California", CityId = 796, Name = "Redding" }
            }
        };
    }
}
