// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class RiversideSanBernardinoOntarioCa
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "riverside-san-bernardino-ontario-ca",
            Name = "Riverside–San Bernardino–Ontario, CA",
            ShortName = "Riverside",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 4744214,
            CsaId = "csa-los-angeles-long-beach-ca",
            Latitude = "33.95335000",
            Longitude = "-117.39616000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 6, StateName = "California", CityId = 817, Name = "Riverside" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 6, StateName = "California", CityId = 847, Name = "San Bernardino" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 6, StateName = "California", CityId = 705, Name = "Ontario" }
            }
        };
    }
}
