// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class RockfordIl
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "rockford-il",
            Name = "Rockford, IL",
            ShortName = "Rockford",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 337103,
            CsaId = "csa-rockford-freeport-rochelle-il",
            Latitude = "42.27113000",
            Longitude = "-89.09400000",
            TimeZoneId = "America/Chicago",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 16, StateName = "Illinois", CityId = 660, Name = "Rockford" }
            }
        };
    }
}
