// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class ToledoOh
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "toledo-oh",
            Name = "Toledo, OH",
            ShortName = "Toledo",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 601396,
            CsaId = null,
            Latitude = "41.66394000",
            Longitude = "-83.55521000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 39, StateName = "Ohio", CityId = 661, Name = "Toledo" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 39, StateName = "Ohio", CityId = 652, Name = "Sylvania" }
            }
        };
    }
}
