// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class TucsonAz
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "tucson-az",
            Name = "Tucson, AZ",
            ShortName = "Tucson",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 1080149,
            CsaId = "csa-tucson-nogales-az",
            Latitude = "32.22174000",
            Longitude = "-110.92648000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 4, StateName = "Arizona", CityId = 204, Name = "Tucson" }
            }
        };
    }
}
