// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class UsBos
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "us-bos",
            Name = "Boston–Cambridge–Newton",
            ShortName = "Boston",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = "14460",
            Type = MetroAreaType.Msa,
            Population = 5025517,
            CsaId = "csa-boston-worcester-providence-ma-ri-nh",
            Latitude = "42.35843000",
            Longitude = "-71.05977000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 24, StateName = "Massachusetts", CityId = 42, Name = "Boston" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 24, StateName = "Massachusetts", CityId = 57, Name = "Cambridge" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 24, StateName = "Massachusetts", CityId = 279, Name = "Quincy" }
            }
        };
    }
}
