// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    public static class UsDc
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "us-dc",
            Name = "Washington–Arlington–Alexandria",
            ShortName = "Washington, D.C.",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = "47900",
            Type = MetroAreaType.Msa,
            Population = 6436489,
            CsaId = "csa-washington-baltimore-arlington-dc-md-va-wv-pa",
            Latitude = "38.90719000",
            Longitude = "-77.03687000",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 10, StateName = "District of Columbia", CityId = 4, Name = "Washington D.C." },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 53, StateName = "Virginia", CityId = 19, Name = "Arlington" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 53, StateName = "Virginia", CityId = 6, Name = "Alexandria" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 23, StateName = "Maryland", CityId = 30, Name = "Bethesda" }
            }
        };
    }
}
