// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class UsNyc
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "us-nyc",
            Name = "New York–Newark–Jersey City",
            ShortName = "New York",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = "35620",
            Type = MetroAreaType.Msa,
            Population = 19940274,
            CsaId = "csa-new-york-newark-ny-nj-ct-pa",
            Latitude = "40.71427000",
            Longitude = "-74.00597000",
            TimeZoneId = "America/New_York",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 632, Name = "New York City" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 1044, Name = "Yonkers" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 218, Name = "Jersey City" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 322, Name = "Newark" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 431, Name = "Huntington" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 8, Name = "Asbury Park" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 401, Name = "Red Bank" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 746, Name = "Port Chester" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 429, Name = "Sayreville" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 129, Name = "Englewood" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 965, Name = "Wantagh" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = null, Name = "Belmont Park" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 1008, Name = "Westbury" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 297, Name = "Montclair" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = null, Name = "Holmdel" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 116, Name = "East Rutherford" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 1003, Name = "West Nyack" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 111, Name = "Brookville" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 276, Name = "Elmont" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 305, Name = "Morristown" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 1018, Name = "White Plains" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 714, Name = "Patchogue" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 936, Name = "Uniondale" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 318, Name = "New Brunswick" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 188, Name = "Harrison" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 718, Name = "Peekskill" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 911, Name = "Tarrytown" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 424, Name = "Rutherford" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 88, Name = "Clifton" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 123, Name = "Elizabeth" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 292, Name = "Farmingville" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 33, StateName = "New Jersey", CityId = 357, Name = "Paramus" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 304, Name = "Forest Hills" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 914, Name = "The Bronx" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 19, Name = "Amityville" }
            }
        };
    }
}
