// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Metros
{
    internal static class WatertownFortDrumNy
    {
        public static MetroArea Data { get; } = new()
        {
            Id = "watertown-fort-drum-ny",
            Name = "Watertown–Fort Drum, NY",
            ShortName = "Watertown",
            CountryIso2 = "US",
            Countries = new() { "US" },
            Code = null,
            Type = MetroAreaType.Msa,
            Population = 113140,
            CsaId = null,
            Latitude = "43.97478000",
            Longitude = "-75.91076000",
            TimeZoneId = "America/New_York",
            Members = new()
            {
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 979, Name = "Watertown" },
                new() { Type = MetroMemberType.City, CountryIso2 = "US", StateId = 35, StateName = "New York", CityId = 306, Name = "Fort Drum" }
            }
        };
    }
}
