// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Csas
{
    internal static class CsaCharlotteConcordNcSc
    {
        public static CombinedStatisticalArea Data { get; } = new()
        {
            Id = "csa-charlotte-concord-nc-sc",
            Name = "Charlotte–Concord, NC-SC",
            Code = null,
            CountryIso2 = "US",
            Population = 3471190,
            MetroIds = new() { "charlotte-concord-gastonia-nc-sc", "hickory-lenoir-morganton-nc" }
        };
    }
}
