// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Csas
{
    public static class CsaGainesvilleLakeCityFl
    {
        public static CombinedStatisticalArea Data { get; } = new()
        {
            Id = "csa-gainesville-lake-city-fl",
            Name = "Gainesville–Lake City, FL",
            Code = null,
            CountryIso2 = "US",
            Population = 433757,
            MetroIds = new() { "gainesville-fl" }
        };
    }
}
