// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Csas
{
    public static class CsaHouston
    {
        public static CombinedStatisticalArea Data { get; } = new()
        {
            Id = "csa-houston",
            Name = "Houston–Pasadena, TX",
            Code = null,
            CountryIso2 = "US",
            Population = 7996140,
            MetroIds = new() { "us-hou" }
        };
    }
}
