// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Csas
{
    internal static class CsaJonesboroParagouldAr
    {
        public static CombinedStatisticalArea Data { get; } = new()
        {
            Id = "csa-jonesboro-paragould-ar",
            Name = "Jonesboro–Paragould, AR",
            Code = null,
            CountryIso2 = "US",
            Population = 185080,
            MetroIds = new() { "jonesboro-ar" }
        };
    }
}
