// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Csas
{
    internal static class CsaStLouisStCharlesFarmingtonMoIl
    {
        public static CombinedStatisticalArea Data { get; } = new()
        {
            Id = "csa-st-louis-st-charles-farmington-mo-il",
            Name = "St. Louis–St. Charles–Farmington, MO-IL",
            Code = null,
            CountryIso2 = "US",
            Population = 2915867,
            MetroIds = new() { "st-louis-mo-il" }
        };
    }
}
