// ⚠️ WARNING: This file is automatically generated by scripts/generate-metros.ps1
// DO NOT modify this file manually as it will be overwritten when the script is run again.
// To update the data, modify data/metro-areas.json and run the script.

using System.Collections.Generic;
using ShowsOnSale.World.Models;

namespace ShowsOnSale.World.Data.Csas
{
    internal static class CsaWilliamsportLockHavenPa
    {
        public static CombinedStatisticalArea Data { get; } = new()
        {
            Id = "csa-williamsport-lock-haven-pa",
            Name = "Williamsport–Lock Haven, PA",
            Code = null,
            CountryIso2 = "US",
            Population = 151101,
            MetroIds = new() { "williamsport-pa" }
        };
    }
}
